const deutschSentences_a2_u13 = {
  info: {
    name: 'A2U13',
    learning: 'Sentences',
  },

  content: [
    {
      sentence: 'Kann ich Ihnen helfen?',
      english: 'Can I help you?',
      russian: 'Могу ли я вам помочь?',
      farsi: 'می‌توانم به شما کمک کنم؟',
    },
    {
      sentence: 'Ja, ich brauche eine Waschmaschine.',
      english: 'Yes, I need a washing machine.',
      russian: 'Да, мне нужна стиральная машина.',
      farsi: 'بله، من به یک ماشین لباسشویی نیاز دارم.',
    },
    {
      sentence: 'Was können Sie empfehlen?',
      english: 'What can you recommend?',
      russian: 'Что вы можете порекомендовать?',
      farsi: 'چه چیزی را می‌توانید توصیه کنید؟',
    },
    {
      sentence: 'Wir haben viele verschiedene Typen.',
      english: 'We have many different types.',
      russian: 'У нас есть много разных типов.',
      farsi: 'ما انواع مختلفی داریم.',
    },
    {
      sentence: 'Hier ist zum Beispiel eine Maschine mit viel Platz.',
      english: 'Here, for example, is a machine with a lot of space.',
      russian: 'Вот, например, машина с большим пространством.',
      farsi: 'اینجا، برای مثال، یک ماشین با فضای زیاد است.',
    },
    {
      sentence: 'Sie können 8 kg Wäsche auf einmal waschen.',
      english: 'You can wash 8 kg of laundry at once.',
      russian: 'Вы можете стирать 8 кг белья за один раз.',
      farsi: 'می‌توانید 8 کیلوگرم لباس را یکجا بشویید.',
    },
    {
      sentence: 'Ein anderer Vorteil ist, dass es fünf Jahre Garantie gibt.',
      english: 'Another advantage is that there is a five-year warranty.',
      russian: 'Еще одно преимущество в том, что есть пятилетняя гарантия.',
      farsi: 'یک مزیت دیگر این است که پنج سال ضمانت دارد.',
    },
    {
      sentence: 'Aber der Preis ist ein Nachteil.',
      english: 'But the price is a disadvantage.',
      russian: 'Но цена — это недостаток.',
      farsi: 'اما قیمت یک نقطه ضعف است.',
    },
    {
      sentence: 'Er ist sehr hoch. Und so viel Wäsche habe ich nicht.',
      english: "It is very high. And I don't have that much laundry.",
      russian: 'Он очень высокий. И у меня нет столько белья.',
      farsi: 'خیلی زیاد است. و من اینقدر لباس ندارم.',
    },
    {
      sentence: 'Was ist mit dieser Waschmaschine?',
      english: 'What about this washing machine?',
      russian: 'А как насчет этой стиральной машины?',
      farsi: 'این ماشین لباسشویی چطور است؟',
    },
    {
      sentence: 'Sie kostet nur 269 Euro.',
      english: 'It costs only 269 euros.',
      russian: 'Она стоит всего 269 евро.',
      farsi: 'فقط 269 یورو هزینه دارد.',
    },
    {
      sentence: 'Ja, aber sie hat weniger Platz und nur zwei Jahre Garantie.',
      english: 'Yes, but it has less space and only a two-year warranty.',
      russian: 'Да, но у нее меньше места и только двухлетняя гарантия.',
      farsi: 'بله، اما فضای کمتری دارد و فقط دو سال ضمانت.',
    },
    {
      sentence:
        'Das macht nichts, die Garantiezeit ist für mich in Ordnung und ich sehe, dass sie genauso energiesparend ist wie die andere Maschine.',
      english:
        "That's okay, the warranty period is fine for me and I see that it is just as energy-efficient as the other machine.",
      russian:
        'Это не важно, срок гарантии для меня в порядке, и я вижу, что она такая же энергоэффективная, как и другая машина.',
      farsi: 'این اهمیتی ندارد، مدت ضمانت برای من مشکلی ندارد و می‌بینم که به اندازه ماشین دیگر انرژی‌بخش است.',
    },
    {
      sentence: 'Der Energieverbrauch ist für mich auch sehr wichtig.',
      english: 'Energy consumption is also very important to me.',
      russian: 'Потребление энергии для меня тоже очень важно.',
      farsi: 'مصرف انرژی برای من هم بسیار مهم است.',
    },
    {
      sentence: 'Ich glaube, die nehme ich.',
      english: "I think I'll take it.",
      russian: 'Я думаю, я возьму это.',
      farsi: 'فکر می‌کنم آن را می‌گیرم.',
    },
    {
      sentence: 'Sollen wir Ihnen die Maschine nach Hause liefern?',
      english: 'Should we deliver the machine to your home?',
      russian: 'Нам доставить машину к вам домой?',
      farsi: 'آیا باید ماشین را به خانه شما تحویل دهیم؟',
    },
    {
      sentence: 'Das kostet 50 Euro extra.',
      english: 'That costs 50 euros extra.',
      russian: 'Это стоит дополнительно 50 евро.',
      farsi: 'این 50 یورو اضافی هزینه دارد.',
    },
    {
      sentence: 'Ja, gerne. Ich kann sie nicht selbst transportieren.',
      english: "Yes, please. I can't transport it myself.",
      russian: 'Да, пожалуйста. Я не могу сам ее транспортировать.',
      farsi: 'بله، لطفاً. من نمی‌توانم آن را خودم حمل کنم.',
    },
    {
      sentence: 'Guten Tag, ich habe vor zwei Wochen diesen Staubsauger gekauft, aber er funktioniert leider nicht.',
      english: "Good day, I bought this vacuum cleaner two weeks ago, but unfortunately it doesn't work.",
      russian: 'Добрый день, я купил этот пылесос две недели назад, но, к сожалению, он не работает.',
      farsi: 'روز بخیر، من این جاروبرقی را دو هفته پیش خریدم، اما متأسفانه کار نمی‌کند.',
    },
    {
      sentence: 'Vielleicht ist das Stromkabel defekt?',
      english: 'Maybe the power cord is defective?',
      russian: 'Может быть, неисправен шнур питания?',
      farsi: 'شاید کابل برق معیوب باشد؟',
    },
    {
      sentence: 'Darf ich mal sehen?',
      english: 'May I see?',
      russian: 'Могу я посмотреть?',
      farsi: 'می‌توانم ببینم؟',
    },
    {
      sentence: 'Ja, hier. Probieren Sie es einmal.',
      english: 'Yes, here. Try it once.',
      russian: 'Да, вот. Попробуйте один раз.',
      farsi: 'بله، اینجا. یک بار امتحان کنید.',
    },
    {
      sentence: 'Hm, da gibt es ein Problem.',
      english: 'Hm, there is a problem.',
      russian: 'Хм, есть проблема.',
      farsi: 'هم، مشکلی وجود دارد.',
    },
    {
      sentence: 'Der Staubsauger hat einen Fehler.',
      english: 'The vacuum cleaner has a fault.',
      russian: 'У пылесоса есть неисправность.',
      farsi: 'جاروبرقی مشکل دارد.',
    },
    {
      sentence: 'Und was passiert jetzt?',
      english: 'And what happens now?',
      russian: 'А что теперь?',
      farsi: 'و حالا چه اتفاقی می‌افتد؟',
    },
    {
      sentence: 'Wir schicken den Staubsauger ans Werk.',
      english: 'We send the vacuum cleaner to the factory.',
      russian: 'Мы отправляем пылесос на завод.',
      farsi: 'ما جاروبرقی را به کارخانه می‌فرستیم.',
    },
    {
      sentence: 'Die prüfen und reparieren ihn.',
      english: 'They will check and repair it.',
      russian: 'Они проверят и отремонтируют его.',
      farsi: 'آنها آن را بررسی و تعمیر می‌کنند.',
    },
    {
      sentence: 'Haben Sie die Quittung?',
      english: 'Do you have the receipt?',
      russian: 'У вас есть квитанция?',
      farsi: 'آیا رسید دارید؟',
    },
    {
      sentence: 'Ja, hier sind die Quittung und der Garantieschein.',
      english: 'Yes, here are the receipt and the warranty card.',
      russian: 'Да, вот квитанция и гарантийный талон.',
      farsi: 'بله، اینجا رسید و کارت ضمانت است.',
    },
    {
      sentence: 'Wann bekomme ich den Staubsauger zurück?',
      english: 'When will I get the vacuum cleaner back?',
      russian: 'Когда я получу пылесос обратно?',
      farsi: 'چه زمانی جاروبرقی را پس می‌گیرم؟',
    },
    {
      sentence: 'Das geht schnell.',
      english: 'That goes quickly.',
      russian: 'Это будет быстро.',
      farsi: 'این به سرعت انجام می‌شود.',
    },
    {
      sentence: 'Sie bekommen Ihren Staubsauger in zwei Wochen zurück.',
      english: 'You will get your vacuum cleaner back in two weeks.',
      russian: 'Вы получите свой пылесос обратно через две недели.',
      farsi: 'شما جاروبرقی خود را در دو هفته پس می‌گیرید.',
    },
    {
      sentence: 'Der Rasierapparat funktioniert nicht.',
      english: "The razor doesn't work.",
      russian: 'Электробритва не работает.',
      farsi: 'ماشین ریش‌تراش کار نمی‌کند.',
    },
    {
      sentence: 'Bitte lassen Sie ihn prüfen und reparieren.',
      english: 'Please have it checked and repaired.',
      russian: 'Пожалуйста, проверьте и отремонтируйте его.',
      farsi: 'لطفاً آن را بررسی و تعمیر کنید.',
    },
    {
      sentence: 'Bitte schicken Sie ihn ans Werk.',
      english: 'Please send it to the factory.',
      russian: 'Пожалуйста, отправьте его на завод.',
      farsi: 'لطفاً آن را به کارخانه بفرستید.',
    },
    {
      sentence: 'Hier ist die Quittung.',
      english: 'Here is the receipt.',
      russian: 'Вот квитанция.',
      farsi: 'اینجا رسید است.',
    },
    {
      sentence: 'Und das ist der Garantieschein.',
      english: 'And this is the warranty card.',
      russian: 'А вот гарантийный талон.',
      farsi: 'و این کارت ضمانت است.',
    },
    {
      sentence: 'Wie lange dauert die Reparatur?',
      english: 'How long does the repair take?',
      russian: 'Сколько времени займет ремонт?',
      farsi: 'تعمیر چقدر طول می‌کشد؟',
    },
  ],
};
export default deutschSentences_a2_u13;
