const deutschSentences_a2_u02 = {
  info: {
    name: 'A2U02',
    learning: 'Sentences',
  },

  content: [
    {
      sentence: 'Praxis Dr. Ortac, Karimi am Apparat, guten Tag.',
      english: "Dr. Ortac's practice, Karimi speaking, good day.",
      russian: 'Практика доктора Ортака, Карими у телефона, добрый день.',
      farsi: 'مطب دکتر اورتاک، کاریمی صحبت می‌کند، روز بخیر.',
    },
    {
      sentence: 'Unser Thema heute: Wie wichtig ist das Internet für den Alltag?',
      english: 'Our topic today: How important is the internet for everyday life?',
      russian: 'Наша тема сегодня: Насколько важен интернет в повседневной жизни?',
      farsi: 'موضوع امروز ما: اینترنت چقدر برای زندگی روزمره مهم است؟',
    },
    {
      sentence: 'Den ganzen Tag online sein.',
      english: 'Being online all day.',
      russian: 'Быть онлайн весь день.',
      farsi: 'تمام روز آنلاین بودن.',
    },
    {
      sentence: 'Immer erreichbar sein.',
      english: 'Always being reachable.',
      russian: 'Всегда быть доступным.',
      farsi: 'همیشه در دسترس بودن.',
    },
    {
      sentence: 'Immer informiert sein.',
      english: 'Always being informed.',
      russian: 'Всегда быть информированным.',
      farsi: 'همیشه مطلع بودن.',
    },
    {
      sentence: 'Das ist möglich, aber wollen wir das?',
      english: 'That is possible, but do we want that?',
      russian: 'Это возможно, но хотим ли мы этого?',
      farsi: 'این ممکن است، اما آیا ما آن را می‌خواهیم؟',
    },
    {
      sentence: 'Das diskutieren wir heute mit unseren Studiogästen “Herrn Merz, Frau Tanner und Julian Demke”.',
      english: "We are discussing this today with our studio guests 'Mr. Merz, Ms. Tanner, and Julian Demke'.",
      russian:
        'Сегодня мы обсуждаем это с нашими гостями в студии «господином Мерцем, госпожой Таннер и Джулианом Демке».',
      farsi: 'امروز این موضوع را با مهمانان استودیوی خود «آقای مرز، خانم تانر و جولیان دمکه» بحث می‌کنیم.',
    },
    {
      sentence: 'Herzlich willkommen!',
      english: 'Welcome!',
      russian: 'Добро пожаловать!',
      farsi: 'خوش آمدید!',
    },
    {
      sentence: 'Herr Merz, wie wichtig ist das Internet für Sie?',
      english: 'Mr. Merz, how important is the internet to you?',
      russian: 'Господин Мерц, насколько важен для вас интернет?',
      farsi: 'آقای مرز، اینترنت برای شما چقدر مهم است؟',
    },
    {
      sentence: 'Ich bin Übersetzer von Beruf.',
      english: 'I am a translator by profession.',
      russian: 'Я переводчик по профессии.',
      farsi: 'من مترجم حرفه‌ای هستم.',
    },
    {
      sentence: 'Ich arbeite sehr viel mit dem Internet.',
      english: 'I work a lot with the internet.',
      russian: 'Я много работаю с интернетом.',
      farsi: 'من زیاد با اینترنت کار می‌کنم.',
    },
    {
      sentence: 'Ich recherchiere Informationen und benutze auch manchmal die Online-Wörterbücher.',
      english: 'I research information and also sometimes use online dictionaries.',
      russian: 'Я ищу информацию и иногда использую онлайн-словари.',
      farsi: 'من اطلاعات جستجو می‌کنم و گاهی اوقات از دیکشنری‌های آنلاین استفاده می‌کنم.',
    },
    {
      sentence: 'Und der Kontakt mit meinen Kunden geht auch über das Internet.',
      english: 'And the contact with my clients is also through the internet.',
      russian: 'И связь с моими клиентами тоже осуществляется через интернет.',
      farsi: 'و ارتباط با مشتریانم نیز از طریق اینترنت است.',
    },
    {
      sentence: 'Ich habe Kunden in ganz Europa, ich kann nicht überall hinfahren.',
      english: "I have clients all over Europe, I can't travel everywhere.",
      russian: 'У меня клиенты по всей Европе, я не могу везде ездить.',
      farsi: 'من در سراسر اروپا مشتری دارم، نمی‌توانم به همه جا سفر کنم.',
    },
    {
      sentence: 'Ich finde das Internet praktisch, weil der Kontakt per E-Mail unkompliziert und schnell ist.',
      english: 'I find the internet practical because contact via email is straightforward and fast.',
      russian: 'Я считаю интернет удобным, потому что связь по электронной почте проста и быстра.',
      farsi: 'اینترنت را عملی می‌دانم زیرا ارتباط از طریق ایمیل ساده و سریع است.',
    },
    {
      sentence: 'Das ist sehr wichtig für mich.',
      english: 'That is very important to me.',
      russian: 'Это очень важно для меня.',
      farsi: 'این برای من بسیار مهم است.',
    },
    {
      sentence: 'Ich habe mobiles Internet, ich muss nicht immer im Büro sitzen.',
      english: "I have mobile internet, I don't always have to sit in the office.",
      russian: 'У меня есть мобильный интернет, мне не нужно всегда сидеть в офисе.',
      farsi: 'من اینترنت همراه دارم، همیشه مجبور نیستم در دفتر بنشینم.',
    },
    {
      sentence: 'Ich kann auch im Zug arbeiten, dann verliere ich keine Zeit.',
      english: "I can also work on the train, then I don't lose any time.",
      russian: 'Я могу работать и в поезде, тогда я не теряю время.',
      farsi: 'می‌توانم در قطار هم کار کنم، در این صورت وقت را از دست نمی‌دهم.',
    },
    {
      sentence: 'Ohne Internet ist das nicht möglich.',
      english: 'Without the internet, that is not possible.',
      russian: 'Без интернета это невозможно.',
      farsi: 'بدون اینترنت، این ممکن نیست.',
    },
    {
      sentence: 'Und natürlich chatte ich auch mit meinen Freunden und habe viele private Kontakte im Internet.',
      english: 'And of course, I also chat with my friends and have many private contacts on the internet.',
      russian: 'И, конечно, я также общаюсь с друзьями и у меня много личных контактов в интернете.',
      farsi: 'و البته، با دوستانم نیز چت می‌کنم و تماس‌های خصوصی زیادی در اینترنت دارم.',
    },
    {
      sentence: 'In anderen Städten suche ich mir auch Restaurants im Internet.',
      english: 'In other cities, I also look for restaurants on the internet.',
      russian: 'В других городах я также ищу рестораны в интернете.',
      farsi: 'در شهرهای دیگر نیز رستوران‌ها را در اینترنت جستجو می‌کنم.',
    },
    {
      sentence: 'Das finde ich wirklich praktisch.',
      english: 'I find that really practical.',
      russian: 'Я нахожу это действительно удобным.',
      farsi: 'این را واقعاً عملی می‌دانم.',
    },
    {
      sentence: 'Frau Tanner, Sie sind jetzt 70 Jahre und sind Rentnerin.',
      english: 'Ms. Tanner, you are now 70 years old and retired.',
      russian: 'Госпожа Таннер, вам сейчас 70 лет, и вы на пенсии.',
      farsi: 'خانم تانر، شما اکنون 70 ساله هستید و بازنشسته‌اید.',
    },
    {
      sentence: 'Sie waren Erzieherin und haben im Kindergarten gearbeitet.',
      english: 'You were a teacher and worked in a kindergarten.',
      russian: 'Вы были воспитателем и работали в детском саду.',
      farsi: 'شما معلم بودید و در مهدکودک کار می‌کردید.',
    },
    {
      sentence: 'Wie wichtig ist das Internet für Sie?',
      english: 'How important is the internet to you?',
      russian: 'Насколько важен для вас интернет?',
      farsi: 'اینترنت برای شما چقدر مهم است؟',
    },
    {
      sentence: 'Im Beruf habe ich noch kein Internet gebraucht, heute ist das anders.',
      english: "I didn't need the internet in my profession, today it is different.",
      russian: 'В своей профессии мне не нужен был интернет, сегодня это по-другому.',
      farsi: 'در حرفه‌ام به اینترنت نیاز نداشتم، امروز این طور نیست.',
    },
    {
      sentence:
        'In vielen Kindergärten gibt es Computer, die Kinder spielen Computerspiele und viele gehen auch schon ins Internet.',
      english:
        'In many kindergartens there are computers, the children play computer games and many also go on the internet.',
      russian:
        'Во многих детских садах есть компьютеры, дети играют в компьютерные игры и многие уже заходят в интернет.',
      farsi:
        'در بسیاری از مهدکودک‌ها کامپیوتر وجود دارد، کودکان بازی‌های کامپیوتری انجام می‌دهند و بسیاری نیز به اینترنت می‌روند.',
    },
    {
      sentence: 'Aber früher war das anders.',
      english: 'But it was different before.',
      russian: 'Но раньше было по-другому.',
      farsi: 'اما قبلاً این طور نبود.',
    },
    {
      sentence: 'In meinem Kindergarten waren keine Computer.',
      english: 'There were no computers in my kindergarten.',
      russian: 'В моем детском саду не было компьютеров.',
      farsi: 'در مهدکودک من کامپیوتر وجود نداشت.',
    },
    {
      sentence: 'Wir haben vorgelesen oder gespielt.',
      english: 'We read aloud or played.',
      russian: 'Мы читали вслух или играли.',
      farsi: 'ما بلندخوانی می‌کردیم یا بازی می‌کردیم.',
    },
    {
      sentence: 'Einen Computer habe ich nicht gebraucht.',
      english: "I didn't need a computer.",
      russian: 'Мне не нужен был компьютер.',
      farsi: 'به کامپیوتر نیاز نداشتم.',
    },
    {
      sentence:
        'Aber jetzt habe ich mir ein Tablet gekauft und finde es wunderbar, weil man so viel im Internet machen kann.',
      english: 'But now I have bought a tablet and find it wonderful because you can do so much on the internet.',
      russian: 'Но сейчас я купила планшет и нахожу это замечательным, потому что можно так много делать в интернете.',
      farsi: 'اما اکنون یک تبلت خریده‌ام و آن را عالی می‌دانم زیرا می‌توان کارهای زیادی در اینترنت انجام داد.',
    },
    {
      sentence: 'Und ich gehe auch viel ins Internet.',
      english: 'And I go on the internet a lot.',
      russian: 'И я много захожу в интернет.',
      farsi: 'و زیاد به اینترنت می‌روم.',
    },
    {
      sentence: 'Ich kaufe gerne online ein, ich sehe Filme und ich gehe gerne auf Twitter.',
      english: 'I like shopping online, I watch movies and I like going on Twitter.',
      russian: 'Я люблю делать покупки онлайн, я смотрю фильмы и мне нравится заходить в Твиттер.',
      farsi: 'من خرید آنلاین را دوست دارم، فیلم می‌بینم و دوست دارم به توییتر بروم.',
    },
    {
      sentence: 'Das finde ich interessant.',
      english: 'I find that interesting.',
      russian: 'Я нахожу это интересным.',
      farsi: 'این را جالب می‌دانم.',
    },
    {
      sentence: 'Ohne Internet ist das Leben viel langweiliger.',
      english: 'Without the internet, life is much more boring.',
      russian: 'Без интернета жизнь намного скучнее.',
      farsi: 'بدون اینترنت، زندگی خیلی کسل‌کننده‌تر است.',
    },
    {
      sentence: 'Und jetzt zu dir, Julian, du bist hier am jüngsten, gerade 16 Jahre alt.',
      english: 'And now to you, Julian, you are the youngest here, just 16 years old.',
      russian: 'А теперь к тебе, Джулиан, ты здесь самый молодой, тебе всего 16 лет.',
      farsi: 'و حالا به تو، جولیان، تو اینجا جوان‌ترین هستی، فقط 16 سال داری.',
    },
    {
      sentence: 'Bist du oft im Internet?',
      english: 'Are you often on the internet?',
      russian: 'Ты часто бываешь в интернете?',
      farsi: 'آیا اغلب در اینترنت هستی؟',
    },
    {
      sentence: 'Ja, klar. Ich habe ein Smartphone mit mobilem Internet.',
      english: 'Yes, of course. I have a smartphone with mobile internet.',
      russian: 'Да, конечно. У меня есть смартфон с мобильным интернетом.',
      farsi: 'بله، البته. من یک گوشی هوشمند با اینترنت همراه دارم.',
    },
    {
      sentence: 'Da bin ich immer im Internet.',
      english: 'I am always on the internet.',
      russian: 'Я всегда в интернете.',
      farsi: 'من همیشه در اینترنت هستم.',
    },
    {
      sentence: 'Und was machst du im Internet?',
      english: 'And what do you do on the internet?',
      russian: 'А что ты делаешь в интернете?',
      farsi: 'و در اینترنت چه کار می‌کنی؟',
    },
    {
      sentence: 'Alles, chatten, spielen, Nachrichten schicken, Fotos posten, recherchieren ... alles halt.',
      english: 'Everything, chatting, playing, sending messages, posting photos, researching ... everything.',
      russian: 'Все: общаюсь, играю, отправляю сообщения, выкладываю фотографии, ищу информацию ... все.',
      farsi: 'همه چیز، چت کردن، بازی کردن، ارسال پیام، پست کردن عکس‌ها، تحقیق کردن ... همه چیز.',
    },
    {
      sentence: 'Brauchst du das Internet auch für die Schule?',
      english: 'Do you also need the internet for school?',
      russian: 'Тебе тоже нужен интернет для школы?',
      farsi: 'آیا برای مدرسه هم به اینترنت نیاز داری؟',
    },
    {
      sentence: 'Ja, ich muss oft etwas recherchieren, für die Hausaufgaben oder für ein Referat.',
      english: 'Yes, I often have to research something, for homework or for a presentation.',
      russian: 'Да, мне часто нужно что-то искать для домашнего задания или для презентации.',
      farsi: 'بله، اغلب باید برای تکالیف یا یک ارائه چیزی تحقیق کنم.',
    },
    {
      sentence: 'Bei Wikipedia kann man gute Informationen finden.',
      english: 'You can find good information on Wikipedia.',
      russian: 'На Википедии можно найти хорошую информацию.',
      farsi: 'می‌توانید اطلاعات خوبی در ویکی‌پدیا پیدا کنید.',
    },
    {
      sentence: 'Kannst du auch mal einen Tag ohne Internet?',
      english: 'Can you also go a day without the internet?',
      russian: 'Можешь ли ты провести день без интернета?',
      farsi: 'آیا می‌توانی یک روز بدون اینترنت بگذرانی؟',
    },
    {
      sentence:
        'Ohne Internet? Nein, das ist die Katastrophe, weil ich dann keinen Kontakt mit meinen Freunden haben kann!',
      english: "Without internet? No, that is a catastrophe, because then I can't have any contact with my friends!",
      russian: 'Без интернета? Нет, это катастрофа, потому что я тогда не смогу общаться с друзьями!',
      farsi: 'بدون اینترنت؟ نه، این فاجعه است، زیرا نمی‌توانم با دوستانم تماس داشته باشم!',
    },
    {
      sentence: 'Guten Abend, meine Damen und Herren, das Diskussionsthema heute ist das Fernsehen.',
      english: 'Good evening, ladies and gentlemen, the discussion topic today is television.',
      russian: 'Добрый вечер, дамы и господа, тема обсуждения сегодня - телевидение.',
      farsi: 'عصر بخیر، خانم‌ها و آقایان، موضوع بحث امروز تلویزیون است.',
    },
    {
      sentence: 'Was ist positiv, was ist negativ?',
      english: 'What is positive, what is negative?',
      russian: 'Что положительное, что отрицательное?',
      farsi: 'چه چیزی مثبت است، چه چیزی منفی است؟',
    },
    {
      sentence: 'Unsere Gäste im Studio: Frau Hegel,Frau Gül, Herr Arndt und Herr Mazur.',
      english: 'Our guests in the studio: Ms. Hegel, Ms. Gül, Mr. Arndt, and Mr. Mazur.',
      russian: 'Наши гости в студии: госпожа Хегель, госпожа Гюль, господин Арндт и господин Мазур.',
      farsi: 'مهمانان ما در استودیو: خانم هگل، خانم گل، آقای آرنت و آقای مازور.',
    },
    {
      sentence: 'Frau Hegel, möchten Sie beginnen?',
      english: 'Ms. Hegel, would you like to start?',
      russian: 'Госпожа Хегель, хотите начать?',
      farsi: 'خانم هگل، مایلید شروع کنید؟',
    },
    {
      sentence: 'Ein kurzes Statement. Was ist Ihre Meinung? Was ist positiv und was ist negativ?',
      english: 'A brief statement. What is your opinion? What is positive and what is negative?',
      russian: 'Краткое заявление. Каково ваше мнение? Что положительное и что отрицательное?',
      farsi: 'یک بیانیه کوتاه. نظر شما چیست؟ چه چیزی مثبت است و چه چیزی منفی است؟',
    },
    {
      sentence: 'Ja, also das Fernsehen bietet gute Informationen.',
      english: 'Yes, well, television provides good information.',
      russian: 'Да, ну, телевидение предоставляет хорошую информацию.',
      farsi: 'بله، خوب، تلویزیون اطلاعات خوبی ارائه می‌دهد.',
    },
    {
      sentence: 'Und ich mag auch die Tiersendungen.',
      english: 'And I also like the animal programs.',
      russian: 'И мне также нравятся программы о животных.',
      farsi: 'و من برنامه‌های حیوانات را نیز دوست دارم.',
    },
    {
      sentence: 'Na ja, im Radio gibt es mehr Informationssendungen.',
      english: 'Well, there are more information programs on the radio.',
      russian: 'Ну, на радио больше информационных программ.',
      farsi: 'خب، برنامه‌های اطلاعاتی بیشتری در رادیو وجود دارد.',
    },
    {
      sentence: 'Die Unterhaltung ist im Fernsehen nicht schlecht, aber die guten Sendungen kommen immer sehr spät.',
      english: 'The entertainment on television is not bad, but the good programs always come very late.',
      russian: 'Развлекательные программы на телевидении неплохие, но хорошие передачи идут всегда очень поздно.',
      farsi: 'سرگرمی‌ها در تلویزیون بد نیستند، اما برنامه‌های خوب همیشه خیلی دیر پخش می‌شوند.',
    },
    {
      sentence: 'Ich sehe das Fernsehen nicht so positiv.',
      english: "I don't see television as very positive.",
      russian: 'Я не считаю телевидение очень положительным.',
      farsi: 'من تلویزیون را خیلی مثبت نمی‌بینم.',
    },
    {
      sentence: 'Es gibt zu viel Werbung.',
      english: 'There is too much advertising.',
      russian: 'Слишком много рекламы.',
      farsi: 'تبلیغات زیادی وجود دارد.',
    },
    {
      sentence: 'Und für Kinder ist das Fernsehen nicht gut.',
      english: 'And television is not good for children.',
      russian: 'И телевидение не полезно для детей.',
      farsi: 'و تلویزیون برای کودکان خوب نیست.',
    },
    {
      sentence: 'Es gibt gute Sendungen für die ganze Familie.',
      english: 'There are good programs for the whole family.',
      russian: 'Есть хорошие передачи для всей семьи.',
      farsi: 'برنامه‌های خوبی برای کل خانواده وجود دارد.',
    },
    {
      sentence: 'Kinder lernen in den Kindersendungen viel.',
      english: "Children learn a lot in children's programs.",
      russian: 'Дети много учатся из детских программ.',
      farsi: 'کودکان در برنامه‌های کودک چیزهای زیادی یاد می‌گیرند.',
    },
    {
      sentence: 'Das finde ich positiv.',
      english: 'I find that positive.',
      russian: 'Я нахожу это положительным.',
      farsi: 'من این را مثبت می‌دانم.',
    },
    {
      sentence:
        'Der Arbeitstag war hart, Sie kommen müde nach Hause, Sie schalten den Fernseher ein - und dann ist es Zeit für den Büning-Abendtee, einen Tee aus dem Hause Büning.',
      english:
        "The workday was hard, you come home tired, you turn on the TV - and then it's time for Büning evening tea, a tea from the Büning house.",
      russian:
        'Рабочий день был тяжелым, вы приходите домой усталым, включаете телевизор - и тогда наступает время вечернего чая Büning, чая из дома Büning.',
      farsi:
        'روز کاری سخت بود، خسته به خانه می‌آیید، تلویزیون را روشن می‌کنید - و سپس زمان نوشیدن چای عصرانه Büning، یک چای از خانه Büning است.',
    },
    {
      sentence: 'Jetzt 100 Gramm für nur 2,99 Euro.',
      english: 'Now 100 grams for only 2.99 euros.',
      russian: 'Теперь 100 граммов всего за 2,99 евро.',
      farsi: 'اکنون 100 گرم فقط برای 2.99 یورو.',
    },
    {
      sentence: 'Trinken Sie den Büning-Abendtee und der Abend wird gemütlich.',
      english: 'Drink Büning evening tea and the evening will be cozy.',
      russian: 'Пейте вечерний чай Büning, и вечер станет уютным.',
      farsi: 'چای عصرانه Büning را بنوشید و عصر راحتی خواهید داشت.',
    },
    {
      sentence: 'Sie kommen von der Arbeit und sind müde - und dann das ... Das muss nicht sein!',
      english: "You come home from work and are tired - and then this ... That doesn't have to be!",
      russian: 'Вы приходите с работы и устали - и потом это ... Этого не должно быть!',
      farsi: 'از سر کار به خانه می‌آیید و خسته‌اید - و سپس این ... نباید اینطور باشد!',
    },
    {
      sentence: 'Kommen Sie zu Elektro-Hanser.',
      english: 'Come to Elektro-Hanser.',
      russian: 'Приходите в Elektro-Hanser.',
      farsi: 'به Elektro-Hanser بیایید.',
    },
    {
      sentence: 'Superangebote für moderne Elektronik.',
      english: 'Great deals for modern electronics.',
      russian: 'Отличные предложения на современную электронику.',
      farsi: 'پیشنهادات عالی برای الکترونیک مدرن.',
    },
    {
      sentence: 'Zum Beispiel Fernseher: jetzt nur 279 Euro.',
      english: 'For example, televisions: now only 279 euros.',
      russian: 'Например, телевизоры: сейчас всего 279 евро.',
      farsi: 'برای مثال، تلویزیون‌ها: اکنون فقط 279 یورو.',
    },
    {
      sentence: 'Geöffnet montags bis samstags von 10 bis 20 Uhr, donnerstags auch bis 22 Uhr.',
      english: 'Open Monday to Saturday from 10 am to 8 pm, also until 10 pm on Thursdays.',
      russian: 'Открыто с понедельника по субботу с 10 до 20 часов, также до 22 часов по четвергам.',
      farsi: 'باز است از دوشنبه تا شنبه از ساعت 10 تا 20، همچنین پنجشنبه‌ها تا ساعت 22.',
    },
    {
      sentence: 'Elektro-Hanser, 25 Filialen in ganz Deutschland.',
      english: 'Elektro-Hanser, 25 branches throughout Germany.',
      russian: 'Elektro-Hanser, 25 филиалов по всей Германии.',
      farsi: 'Elektro-Hanser، 25 شعبه در سراسر آلمان.',
    },
    {
      sentence: 'Auch in Ihrer Nähe.',
      english: 'Also near you.',
      russian: 'Также рядом с вами.',
      farsi: 'همچنین در نزدیکی شما.',
    },
    {
      sentence: 'Müde am Abend?',
      english: 'Tired in the evening?',
      russian: 'Устали вечером?',
      farsi: 'عصرها خسته‌اید؟',
    },
    {
      sentence: 'Stress bei der Arbeit?',
      english: 'Stress at work?',
      russian: 'Стресс на работе?',
      farsi: 'استرس در محل کار؟',
    },
    {
      sentence: 'Mit dem Massagestuhl TechnoRelax" werden Sie wieder fit.',
      english: 'With the TechnoRelax massage chair, you will get fit again.',
      russian: 'С массажным креслом TechnoRelax вы снова станете бодрыми.',
      farsi: 'با صندلی ماساژور TechnoRelax دوباره به تناسب اندام می‌رسید.',
    },
    {
      sentence: 'Sehen Sie gemütlich fern und genießen Sie die wohltuende Massage mit acht Automatikprogrammen!',
      english: 'Watch TV comfortably and enjoy the soothing massage with eight automatic programs!',
      russian:
        'Смотрите телевизор с комфортом и наслаждайтесь успокаивающим массажем с восемью автоматическими программами!',
      farsi: 'به راحتی تلویزیون تماشا کنید و از ماساژ آرام‌بخش با هشت برنامه اتوماتیک لذت ببرید!',
    },
    {
      sentence: 'Besuchen Sie uns auf unserer Internetseite: www.technorelax.de',
      english: 'Visit us on our website: www.technorelax.de',
      russian: 'Посетите наш сайт: www.technorelax.de',
      farsi: 'به وبسایت ما مراجعه کنید: www.technorelax.de',
    },
  ],
};
export default deutschSentences_a2_u02;
