const deutschSentences_a1_u12 = {
  info: {
    name: 'A1U12',
    learning: 'Sentences',
  },

  content: [
    {
      sentence: 'Ich bin Studentin und habe nicht viel Geld.',
      english: "I am a student and don't have much money.",
      russian: 'Я студентка и у меня мало денег.',
      farsi: 'من دانشجو هستم و پول زیادی ندارم.',
    },
    {
      sentence: 'Ich kaufe meine Sachen meistens in Secondhandläden.',
      english: 'I usually buy my things in second-hand stores.',
      russian: 'Я покупаю вещи в секонд-хенде.',
      farsi: 'من معمولاً وسایلم را از فروشگاه‌های دست دوم خریداری می‌کنم.',
    },
    {
      sentence: 'Das ist billig und die Kleidung ist oft originell.',
      english: "It's cheap, and the clothes are often original.",
      russian: 'Это дешево, и одежда часто оригинальна.',
      farsi: 'این ارزان است و لباس‌ها اغلب منحصر به فرد هستند.',
    },
    {
      sentence: 'Ich habe drei Kinder und die brauchen immer etwas Neues.',
      english: 'I have three children, and they always need something new.',
      russian: 'У меня трое детей, и им всегда нужно что-то новое.',
      farsi: 'من سه فرزند دارم و آنها همیشه به چیزهای جدید نیاز دارند.',
    },
    {
      sentence: 'Bei uns gibt es immer einen Flohmarkt für Kindersachen.',
      english: "We always have a flea market for children's items.",
      russian: 'У нас часто проходит блошиный рынок для детских вещей.',
      farsi: 'ما همیشه یک بازار دست دوم برای وسایل کودکان داریم.',
    },
    {
      sentence: 'Da verkaufe ich und kaufe auch.',
      english: 'I sell and buy there too.',
      russian: 'Я там продаю и покупаю тоже.',
      farsi: 'من در آنجا می‌فروشم و خرید هم می‌کنم.',
    },
    {
      sentence: 'Die Sachen sind gut und billig.',
      english: 'The items are good and cheap.',
      russian: 'Вещи хорошие и дешевые.',
      farsi: 'وسایل خوب و ارزان هستند.',
    },
    {
      sentence: 'Manchmal kaufe ich auch etwas im Supermarkt.',
      english: 'Sometimes I also buy something at the supermarket.',
      russian: 'Иногда я покупаю что-то в супермаркете.',
      farsi: 'گاهی هم از سوپرمارکت خرید می‌کنم.',
    },
    {
      sentence: 'Ich gehe nicht gerne einkaufen, außerdem habe ich wenig Zeit.',
      english: "I don't like shopping, and besides, I have little time.",
      russian: 'Я не люблю ходить по магазинам, кроме того, у меня мало времени.',
      farsi: 'من خرید کردن را دوست ندارم و علاوه بر این، وقت کمی دارم.',
    },
    {
      sentence: 'Deshalb bestelle ich meine Kleidung meistens im Internet.',
      english: "That's why I mostly order my clothes online.",
      russian: 'Поэтому я заказываю одежду в основном в интернете.',
      farsi: 'به همین دلیل، من اغلب لباس‌هایم را از اینترنت سفارش می‌دهم.',
    },
    {
      sentence: 'Das ist praktisch und geht schnell.',
      english: "It's convenient and quick.",
      russian: 'Это удобно и быстро.',
      farsi: 'این عملی است و سریع انجام می‌شود.',
    },
    {
      sentence: 'Ich kaufe gern ein, aber Kleidung ist ganz schön teuer.',
      english: 'I like shopping, but clothes are quite expensive.',
      russian: 'Я люблю ходить по магазинам, но одежда довольно дорогая.',
      farsi: 'من خرید کردن را دوست دارم، اما لباس‌ها بسیار گران هستند.',
    },
    {
      sentence:
        'Ich gehe immer in Kaufhäuser oder Boutiquen, da gibt es oft günstige Angebote im Sommerschlussverkauf oder im Winterschlussverkauf.',
      english:
        'I always go to department stores or boutiques; there are often good deals in the summer or winter sales.',
      russian:
        'Я всегда хожу в универмаги или бутики, там часто бывают выгодные предложения на летней или зимней распродаже.',
      farsi:
        'من همیشه به فروشگاه‌های بزرگ یا بوتیک‌ها می‌روم، اغلب در حراجی تابستانه یا زمستانه تخفیف‌های خوبی وجود دارد.',
    },
    {
      sentence: 'Da kann man gute Sachen billig bekommen.',
      english: 'You can get good things cheaply there.',
      russian: 'Там можно купить хорошие вещи дешево.',
      farsi: 'در آنجا می‌توان وسایل خوب را ارزان خرید.',
    },
    {
      sentence: 'Hier gibt es Hosen. Du brauchst eine Hose.',
      english: 'There are pants here. You need a pair of pants.',
      russian: 'Здесь есть брюки. Тебе нужны брюки.',
      farsi: 'اینجا شلوار هست. تو به یک شلوار نیاز داری.',
    },
    {
      sentence: 'Welche Hose möchtest du, die weiße oder die schwarze Hose?',
      english: 'Which pants do you want, the white ones or the black ones?',
      russian: 'Какие брюки ты хочешь, белые или черные?',
      farsi: 'کدام شلوار را می‌خواهی، سفید یا سیاه؟',
    },
    {
      sentence: 'Die schwarze Hose gefällt mir gut.',
      english: 'I like the black pants.',
      russian: 'Черные брюки мне нравятся.',
      farsi: 'من شلوار سیاه را دوست دارم.',
    },
    {
      sentence: 'Und welches T-Shirt findest du gut?',
      english: 'And which T-shirt do you like?',
      russian: 'А какая футболка тебе нравится?',
      farsi: 'و کدام تی‌شرت را دوست داری؟',
    },
    {
      sentence: 'Das schwarze T-Shirt ist gut.',
      english: 'The black T-shirt is good.',
      russian: 'Черная футболка хороша.',
      farsi: 'تی‌شرت سیاه خوب است.',
    },
    {
      sentence: 'Ganz schwarz, ist das nicht langweilig?',
      english: "All black, isn't that boring?",
      russian: 'Все черное, это не скучно?',
      farsi: 'همه چیز سیاه، آیا این خسته‌کننده نیست؟',
    },
    {
      sentence: 'Nein, das ist cool. Alle ziehen das an.',
      english: "No, that's cool. Everyone wears it.",
      russian: 'Нет, это круто. Все так носят.',
      farsi: 'نه، این خیلی باحال است. همه این را می‌پوشند.',
    },
    {
      sentence: 'Entschuldigung, wo finde ich die Toiletten?',
      english: 'Excuse me, where can I find the toilets?',
      russian: 'Извините, где я могу найти туалеты?',
      farsi: 'ببخشید، سرویس بهداشتی کجاست؟',
    },
    {
      sentence: 'Die sind im ersten Stock, direkt neben der Rolltreppe.',
      english: 'They are on the first floor, right next to the escalator.',
      russian: 'Они на первом этаже, прямо рядом с эскалатором.',
      farsi: 'آنها در طبقه اول، درست کنار پله برقی هستند.',
    },
    {
      sentence: 'Ach bitte, wo kann ich das bezahlen?',
      english: 'Oh please, where can I pay for this?',
      russian: 'Пожалуйста, где я могу заплатить?',
      farsi: 'لطفاً، کجا می‌توانم این را پرداخت کنم؟',
    },
    {
      sentence: 'Die Kasse ist dort hinten rechts.',
      english: 'The cash register is at the back on the right.',
      russian: 'Касса там, справа в конце.',
      farsi: 'صندوق در پشت سمت راست است.',
    },
    {
      sentence: 'Entschuldigung, ich suche den Ausgang.',
      english: "Excuse me, I'm looking for the exit.",
      russian: 'Извините, я ищу выход.',
      farsi: 'ببخشید، من به دنبال خروجی می‌گردم.',
    },
    {
      sentence: 'Den Ausgang? Der ist da vorne links.',
      english: "The exit? It's up front to the left.",
      russian: 'Выход? Он впереди слева.',
      farsi: 'خروجی؟ آن جلو سمت چپ است.',
    },
    {
      sentence: 'Haben Sie Computerspiele?',
      english: 'Do you have computer games?',
      russian: 'У вас есть компьютерные игры?',
      farsi: 'آیا بازی‌های کامپیوتری دارید؟',
    },
    {
      sentence: 'Ja, in der Multimedia-Abteilung im dritten Stock.',
      english: 'Yes, in the multimedia department on the third floor.',
      russian: 'Да, в отделе мультимедиа на третьем этаже.',
      farsi: 'بله، در بخش چندرسانه‌ای در طبقه سوم.',
    },
    {
      sentence: 'Wie lange haben Sie geöffnet?',
      english: 'How long are you open?',
      russian: 'До какого времени вы работаете?',
      farsi: 'تا چه ساعتی باز هستید؟',
    },
    {
      sentence: 'Bis 20 Uhr.',
      english: 'Until 8 PM.',
      russian: 'До 8 вечера.',
      farsi: 'تا ساعت ۸ شب.',
    },
    {
      sentence: 'Kann ich Ihnen helfen?',
      english: 'Can I help you?',
      russian: 'Могу я вам помочь?',
      farsi: 'می‌توانم به شما کمک کنم؟',
    },
    {
      sentence: 'Danke, ich schaue nur.',
      english: "Thanks, I'm just looking.",
      russian: 'Спасибо, я просто смотрю.',
      farsi: 'ممنون، من فقط دارم نگاه می‌کنم.',
    },
    {
      sentence: 'Kann ich das Kleid mal anprobieren?',
      english: 'Can I try on the dress?',
      russian: 'Могу я примерить это платье?',
      farsi: 'می‌توانم این لباس را امتحان کنم؟',
    },
    {
      sentence: 'Gerne, die Umkleidekabinen sind da vorne rechts.',
      english: 'Sure, the fitting rooms are up front on the right.',
      russian: 'Конечно, примерочные впереди справа.',
      farsi: 'البته، اتاق‌های پرو در جلو سمت راست هستند.',
    },
    {
      sentence: 'Gibt es den Mantel auch in Größe 40?',
      english: 'Is the coat available in size 40?',
      russian: 'Есть ли пальто в размере 40?',
      farsi: 'آیا این کت در سایز ۴۰ موجود است؟',
    },
    {
      sentence: 'Größe 40? Da muss ich nachsehen. Einen Moment, bitte.',
      english: 'Size 40? I have to check. One moment, please.',
      russian: 'Размер 40? Я должен проверить. Один момент, пожалуйста.',
      farsi: 'سایز ۴۰؟ باید بررسی کنم. یک لحظه لطفاً.',
    },
    {
      sentence: 'Was kostet der braune Mantel? Kostet der auch 59 Euro wie der grüne hier?',
      english: 'How much is the brown coat? Is it also 59 euros like the green one here?',
      russian: 'Сколько стоит коричневое пальто? Оно тоже стоит 59 евро, как и это зеленое?',
      farsi: 'این کت قهوه‌ای چقدر است؟ آیا آن هم ۵۹ یورو مانند این سبز است؟',
    },
    {
      sentence: 'Nein, ich glaube nicht. Ist da kein Preisschild dran?',
      english: "No, I don't think so. Isn't there a price tag on it?",
      russian: 'Нет, я так не думаю. На нем нет ценника?',
      farsi: 'نه، فکر نمی‌کنم. آیا برچسب قیمت ندارد؟',
    },
    {
      sentence: 'Nein, ich sehe keinen Preis.',
      english: "No, I don't see a price.",
      russian: 'Нет, я не вижу цены.',
      farsi: 'نه، قیمتی نمی‌بینم.',
    },
    {
      sentence: 'Moment, ich schaue einmal nach.',
      english: "One moment, I'll check.",
      russian: 'Минуточку, я проверю.',
      farsi: 'یک لحظه، من نگاه می‌کنم.',
    },
    {
      sentence: 'Also, der Mantel ist doch von Leila, oder?',
      english: 'So, the coat is from Leila, right?',
      russian: 'Итак, пальто от Лейлы, верно?',
      farsi: 'پس، کت از لیلا است، درست است؟',
    },
    {
      sentence: 'Der kostet 95,95 Euro.',
      english: 'It costs 95.95 euros.',
      russian: 'Он стоит 95,95 евро.',
      farsi: 'قیمتش ۹۵.۹۵ یورو است.',
    },
    {
      sentence: 'Entschuldigung, haben Sie diese Babyhose auch in Größe 68?',
      english: 'Excuse me, do you have these baby pants in size 68?',
      russian: 'Извините, у вас есть эти детские штаны размера 68?',
      farsi: 'ببخشید، آیا این شلوار نوزاد را در سایز ۶۸ دارید؟',
    },
    {
      sentence: '68? Moment, hier habe ich 86, 80 und 74.',
      english: '68? One moment, I have 86, 80, and 74 here.',
      russian: '68? Минутку, здесь у меня есть 86, 80 и 74.',
      farsi: '۶۸؟ یک لحظه، من ۸۶، ۸۰ و ۷۴ دارم.',
    },
    {
      sentence: 'Nein, tut mir leid, in Größe 68 haben wir die Hose nicht mehr.',
      english: "No, sorry, we don't have the pants in size 68 anymore.",
      russian: 'Извините, у нас больше нет штанов размера 68.',
      farsi: 'نه، متاسفم، در سایز ۶۸ دیگر نداریم.',
    },
    {
      sentence: 'Nehmen Sie doch diese Hose in Größe 74.',
      english: 'Take these pants in size 74 instead.',
      russian: 'Возьмите эти штаны размера 74.',
      farsi: 'این شلوار را در سایز ۷۴ بگیرید.',
    },
    {
      sentence: 'Ja, stimmt, das geht bestimmt auch. Babys wachsen so schnell.',
      english: "Yes, that's right, that will work too. Babies grow so fast.",
      russian: 'Да, верно, это тоже подойдет. Дети так быстро растут.',
      farsi: 'بله، درست است، این هم می‌تواند مناسب باشد. بچه‌ها خیلی سریع رشد می‌کنند.',
    },
    {
      sentence: 'Entschuldigung, wo finde ich Handys?',
      english: 'Excuse me, where can I find cell phones?',
      russian: 'Извините, где я могу найти мобильные телефоны?',
      farsi: 'ببخشید، موبایل‌ها را کجا می‌توانم پیدا کنم؟',
    },
    {
      sentence: 'Entschuldigung, wie lange haben Sie geöffnet?',
      english: 'Excuse me, how long are you open?',
      russian: 'Извините, до какого времени вы работаете?',
      farsi: 'ببخشید، تا چه ساعتی باز هستید؟',
    },
    {
      sentence: 'Ach bitte, wo kann ich das bezahlen?',
      english: 'Oh please, where can I pay for this?',
      russian: 'Пожалуйста, где я могу заплатить?',
      farsi: 'لطفاً، کجا می‌توانم این را پرداخت کنم؟',
    },
    {
      sentence: 'Wo ist die Kasse?',
      english: 'Where is the cash register?',
      russian: 'Где касса?',
      farsi: 'صندوق کجاست؟',
    },
    {
      sentence: 'Entschuldigung, ich suche die Toiletten.',
      english: "Excuse me, I'm looking for the toilets.",
      russian: 'Извините, я ищу туалеты.',
      farsi: 'ببخشید، من به دنبال سرویس بهداشتی می‌گردم.',
    },
    {
      sentence: 'Ich hätte gern die Bluse in Weiß.',
      english: "I'd like the blouse in white.",
      russian: 'Мне нужна белая блузка.',
      farsi: 'من بلوز سفید را می‌خواهم.',
    },
    {
      sentence: 'Entschuldigung, was kostet der Pullover?',
      english: 'Excuse me, how much is the sweater?',
      russian: 'Извините, сколько стоит свитер?',
      farsi: 'ببخشید، این پلوور چقدر است؟',
    },
    {
      sentence: 'Gibt es die Jacke auch in Größe 40?',
      english: 'Is the jacket available in size 40?',
      russian: 'Есть ли куртка в размере 40?',
      farsi: 'آیا کت در سایز ۴۰ موجود است؟',
    },
    {
      sentence: 'Kann ich den Mantel anprobieren?',
      english: 'Can I try on the coat?',
      russian: 'Могу я примерить пальто?',
      farsi: 'می‌توانم کت را امتحان کنم؟',
    },
  ],
};

export default deutschSentences_a1_u12;
