const deutschSentences_a1_u07 = {
  info: {
    name: 'A1U07',
    learning: 'Sentences',
  },

  content: [
    {
      sentence: 'Basketballverein Spandau, Ulrike Rekowski am Apparat. Was kann ich für Sie tun?',
      english: 'Basketball Club Spandau, Ulrike Rekowski speaking. How can I help you?',
      russian: 'Баскетбольный клуб Шпандау, у аппарата Ульрика Рековски. Чем могу вам помочь?',
      farsi: 'باشگاه بسکتبال اسپاندو، اولریک رکوسکی صحبت می‌کند. چگونه می‌توانم به شما کمک کنم؟',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence:
        'Guten Tag, hier spricht Thomas Beeger. Ich brauche Ihre Bankverbindung, denn ich will den Mitgliedsbeitrag überweisen.',
      english:
        'Good day, this is Thomas Beeger. I need your bank details because I want to transfer the membership fee.',
      russian:
        'Добрый день, говорит Томас Бегер. Мне нужны ваши банковские реквизиты, так как я хочу перевести членский взнос.',
      farsi:
        'روز بخیر، اینجا توماس بگر صحبت می‌کند. من به اطلاعات بانکی شما نیاز دارم زیرا می‌خواهم هزینه عضویت را انتقال دهم.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Die IBAN ist DE46 1005 0000 0036 2037 00 bei der Berliner Sparkasse.',
      english: 'The IBAN is DE46 1005 0000 0036 2037 00 at Berliner Sparkasse.',
      russian: 'IBAN: DE46 1005 0000 0036 2037 00 в Berliner Sparkasse.',
      farsi: 'شماره شبا (IBAN) DE46 1005 0000 0036 2037 00 در بانک اسپارکاسه برلین.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Vielen Dank und auf Wiederhören.',
      english: 'Thank you and goodbye.',
      russian: 'Спасибо и до свидания.',
      farsi: 'متشکرم و خداحافظ.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Sprachschule Becker, hier spricht Helene Deck.',
      english: 'Language School Becker, Helene Deck speaking.',
      russian: 'Языковая школа Беккер, говорит Хелене Дек.',
      farsi: 'مدرسه زبان بکر، هلن دک صحبت می‌کند.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence:
        'Guten Tag, mein Name ist Matteo Bernardini. Ich möchte die Gebühr für den B2-Abendkurs überweisen, aber ich kann Ihre Bankverbindung nicht finden.',
      english:
        'Good day, my name is Matteo Bernardini. I want to transfer the fee for the B2 evening course, but I cant find your bank details.',
      russian:
        'Добрый день, меня зовут Маттео Бернардини. Я хочу перевести оплату за вечерний курс B2, но не могу найти ваши банковские реквизиты.',
      farsi:
        'روز بخیر، نام من ماتئو برناردینی است. می‌خواهم هزینه دوره شبانه B2 را واریز کنم، اما نمی‌توانم اطلاعات بانکی شما را پیدا کنم.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Unsere IBAN ist DE87 7706 0100 0025 7000 07 bei der VR-Bank Bamberg.',
      english: 'Our IBAN is DE87 7706 0100 0025 7000 07 at VR-Bank Bamberg.',
      russian: 'Наш IBAN: DE87 7706 0100 0025 7000 07 в VR-Bank Bamberg.',
      farsi: 'شماره شبا (IBAN) ما DE87 7706 0100 0025 7000 07 در بانک VR بامبرگ.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Vielen Dank und auf Wiederhören.',
      english: 'Thank you and goodbye.',
      russian: 'Спасибо и до свидания.',
      farsi: 'متشکرم و خداحافظ.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Frau Deck geht um halb zehn aus dem Haus.',
      english: 'Mrs. Deck leaves the house at half-past nine.',
      russian: 'Фрау Дек выходит из дома в половине десятого.',
      farsi: 'خانم دک ساعت نه و نیم از خانه خارج می‌شود.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Sie geht heute zuerst zum Friseur.',
      english: 'She is going to the hairdresser first today.',
      russian: 'Сегодня она сначала идет к парикмахеру.',
      farsi: 'امروز ابتدا به آرایشگاه می‌رود.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Sie bleibt von zehn bis elf beim Friseur. ',
      english: 'She stays at the hairdresser from ten to eleven.',
      russian: 'Она будет у парикмахера с десяти до одиннадцати.',
      farsi: 'او از ساعت ده تا یازده در آرایشگاه می‌ماند.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Um elf Uhr geht sie vom Friseur zur Arbeit.',
      english: 'At eleven, she goes from the hairdresser to work.',
      russian: 'В одиннадцать она идет от парикмахера на работу.',
      farsi: 'ساعت یازده از آرایشگاه به محل کار می‌رود.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Nach der Arbeit holt sie die Kinder von der Kita ab.',
      english: 'After work, she picks up the children from daycare.',
      russian: 'После работы она забирает детей из детского сада.',
      farsi: 'پس از کار، کودکان را از مهد کودک برمی‌دارد. ',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Sie geht mit den Kindern zusammen einkaufen.',
      english: 'She goes shopping with the children.',
      russian: 'Она идет с детьми за покупками.',
      farsi: 'با کودکان به خرید می‌رود.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Dann gehen sie nach Hause.',
      english: 'Then they go home.',
      russian: 'Потом они идут домой.',
      farsi: ' سپس به خانه باز می‌گردند.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Ihr Mann ist schon zu Hause und macht das Abendessen.',
      english: 'Her husband is already at home and preparing dinner.',
      russian: 'Ее муж уже дома и готовит ужин.',
      farsi: 'شوهرش قبلاً در خانه است و شام را آماده می‌کند.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Findest du deine Arbeit gut?',
      english: 'Do you like your job?',
      russian: 'Тебе нравится твоя работа?',
      farsi: 'آیا از کار خود راضی هستی؟',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Ja, die Arbeit ist wirklich interessant.',
      english: 'Yes, the job is really interesting.',
      russian: 'Да, работа действительно интересная.',
      farsi: 'بله، کار واقعاً جالب است.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Musst du auch mit den Kunden sprechen?',
      english: 'Do you also have to talk to the customers?',
      russian: 'Тебе тоже нужно говорить с клиентами?',
      farsi: 'آیا تو هم باید با مشتریان صحبت کنی؟',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Nein, das macht der Chef. Er hat den Kontakt zu den Kunden.',
      english: 'No, the boss does that. He handles the contact with the customers.',
      russian: 'Нет, этим занимается начальник. Он контактирует с клиентами.',
      farsi: 'نه، رئیس این کار را انجام می‌دهد. او با مشتریان در تماس است.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Kannst du dann nicht zu Hause arbeiten?',
      english: 'Cant you work from home then?',
      russian: 'Ты тогда не можешь работать из дома?',
      farsi: 'آیا نمی‌توانی در خانه کار کنی؟',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Doch, das geht schon. Ich brauche ja nur einen Computer und das Internet.',
      english: 'Yes, that´s possible. I only need a computer and the internet.',
      russian: 'Да, это возможно. Мне нужен только компьютер и интернет.',
      farsi: 'بله، این ممکن است. من فقط به یک کامپیوتر و اینترنت نیاز دارم.',
      audio_de: '',
      descriptions: ``,
    },
    {
      sentence: 'Aber ich will nicht alleine arbeiten. Ich arbeite gern im Team.',
      english: 'But I don´t want to work alone. I like working in a team.',
      russian: 'Но я не хочу работать в одиночку. Мне нравится работать в команде.',
      farsi: 'اما من نمی‌خواهم تنها کار کنم. دوست دارم در تیم کار کنم.',

      audio_de: '',
      descriptions: ``,
    },
  ],
};

export default deutschSentences_a1_u07;
