const deutschSentences_a2_u11 = {
  info: {
    name: 'A2U11',
    learning: 'Sentences',
  },

  content: [
    {
      sentence: 'Was machst du da?',
      english: 'What are you doing there?',
      russian: 'Что ты там делаешь?',
      farsi: 'داری چکار می‌کنی؟',
    },
    {
      sentence: 'Ich sehe mir die Fotos aus unserem letzten Urlaub an.',
      english: "I'm looking at the photos from our last vacation.",
      russian: 'Я смотрю фотографии с нашего последнего отпуска.',
      farsi: 'دارم عکس‌های تعطیلات آخرمان را نگاه می‌کنم.',
    },
    {
      sentence: 'Schau mal, hier sind die Fotos aus dem Restaurant.',
      english: 'Look, here are the photos from the restaurant.',
      russian: 'Смотри, вот фотографии из ресторана.',
      farsi: 'نگاه کن، اینها عکس‌های رستوران هستند.',
    },
    {
      sentence: 'Das ist die Kellnerin, die so gut Deutsch gesprochen hat.',
      english: 'This is the waitress who spoke such good German.',
      russian: 'Это официантка, которая так хорошо говорила по-немецки.',
      farsi: 'این پیشخدمت است که خیلی خوب آلمانی صحبت می‌کرد.',
    },
    {
      sentence: 'Und schau mal hier: Das ist das Museum, das fast immer geschlossen war.',
      english: 'And look here: This is the museum that was almost always closed.',
      russian: 'И смотри здесь: Это музей, который почти всегда был закрыт.',
      farsi: 'و اینجا را نگاه کن: این موزه است که تقریباً همیشه بسته بود.',
    },
    {
      sentence: 'Und dann dieses Foto: Das ist der Strand, der so toll war.',
      english: 'And then this photo: This is the beach that was so great.',
      russian: 'А вот это фото: Это пляж, который был таким замечательным.',
      farsi: 'و سپس این عکس: این ساحل است که خیلی عالی بود.',
    },
    {
      sentence: 'So ruhig und der Sand war so weiß und sauber.',
      english: 'So quiet and the sand was so white and clean.',
      russian: 'Так тихо, и песок был таким белым и чистым.',
      farsi: 'خیلی آرام و شن‌ها خیلی سفید و تمیز بودند.',
    },
    {
      sentence: 'Hier ist noch ein Foto: Das sind die Nachbarn, die uns zum Essen eingeladen haben.',
      english: 'Here is another photo: These are the neighbors who invited us for dinner.',
      russian: 'Вот еще одно фото: Это соседи, которые пригласили нас на ужин.',
      farsi: 'این هم یک عکس دیگر: این همسایگان هستند که ما را برای شام دعوت کردند.',
    },
    {
      sentence: 'Ja, es war wirklich ein schöner Urlaub.',
      english: 'Yes, it was really a nice vacation.',
      russian: 'Да, это был действительно хороший отпуск.',
      farsi: 'بله، واقعاً تعطیلات خوبی بود.',
    },
    {
      sentence: 'Ich möchte dieses Jahr auch wieder ans Meer.',
      english: 'I want to go to the sea again this year.',
      russian: 'Я хочу снова поехать на море в этом году.',
      farsi: 'من می‌خواهم امسال هم دوباره به دریا بروم.',
    },
    {
      sentence: 'Ich würde auch gerne einmal die Türkei kennenlernen.',
      english: 'I would also like to get to know Turkey sometime.',
      russian: 'Я бы тоже хотел познакомиться с Турцией.',
      farsi: 'من هم دوست دارم یک بار ترکیه را ببینم.',
    },
    {
      sentence: 'Sollen wir nicht einen Strandurlaub in der Türkei buchen?',
      english: "Shouldn't we book a beach vacation in Turkey?",
      russian: 'Не забронировать ли нам пляжный отдых в Турции?',
      farsi: 'آیا نباید یک تعطیلات ساحلی در ترکیه رزرو کنیم؟',
    },
    {
      sentence: 'Ja, das würde ich auch gerne machen.',
      english: 'Yes, I would also like to do that.',
      russian: 'Да, я бы тоже хотел это сделать.',
      farsi: 'بله، من هم دوست دارم این کار را بکنم.',
    },
    {
      sentence: 'Sollen wir mal ins Reisebüro gehen?',
      english: 'Should we go to the travel agency?',
      russian: 'Не пойти ли нам в туристическое агентство?',
      farsi: 'آیا باید به یک آژانس مسافرتی برویم؟',
    },
    {
      sentence: 'Gute Idee, das machen wir!',
      english: "Good idea, let's do that!",
      russian: 'Хорошая идея, давай сделаем это!',
      farsi: 'ایده خوبی است، بیا این کار را بکنیم!',
    },
    {
      sentence: 'Am liebsten gleich heute, nach dem Einkaufen.',
      english: 'Preferably today, after shopping.',
      russian: 'Лучше всего сегодня, после покупок.',
      farsi: 'ترجیحاً امروز، بعد از خرید.',
    },
    {
      sentence: "Reisebüro 'Sonnenschein', mein Name ist Welke, was kann ich für Sie tun?",
      english: "Travel agency 'Sunshine', my name is Welke, how can I help you?",
      russian: "Туристическое агентство 'Солнечный свет', меня зовут Вельке, чем я могу вам помочь?",
      farsi: "آژانس مسافرتی 'نور خورشید'، نام من ولکه است، چگونه می‌توانم به شما کمک کنم؟",
    },
    {
      sentence: 'Guten Tag, ich brauche einen Hin- und Rückflug nach Moskau.',
      english: 'Good day, I need a round trip flight to Moscow.',
      russian: 'Добрый день, мне нужен билет туда и обратно в Москву.',
      farsi: 'روز بخیر، من یک پرواز رفت و برگشت به مسکو نیاز دارم.',
    },
    {
      sentence: 'Der Hinflug soll am 4. Mai von München sein und der Rückflug am 7. Mai.',
      english: 'The outbound flight should be on May 4th from Munich and the return flight on May 7th.',
      russian: 'Вылет должен быть 4 мая из Мюнхена, а обратный рейс 7 мая.',
      farsi: 'پرواز رفت باید در 4 می از مونیخ باشد و پرواز برگشت در 7 می.',
    },
    {
      sentence: 'Ich schaue mal ... So, hier habe ich einen Flug, aber der ist ziemlich teuer.',
      english: 'Let me see ... So, here I have a flight, but it is quite expensive.',
      russian: 'Сейчас посмотрю ... Итак, у меня есть рейс, но он довольно дорогой.',
      farsi: 'بگذار ببینم ... اینجا یک پرواز دارم، اما خیلی گران است.',
    },
    {
      sentence: 'Hin- und Rückflug kosten zusammen 538 Euro.',
      english: 'The round trip costs 538 euros in total.',
      russian: 'Билет туда и обратно стоит 538 евро.',
      farsi: 'پرواز رفت و برگشت در مجموع 538 یورو هزینه دارد.',
    },
    {
      sentence: 'Das macht nichts. Ich mache eine Geschäftsreise und die Firma bezahlt.',
      english: "That's okay. I'm on a business trip and the company pays.",
      russian: 'Ничего страшного. Я в командировке, и компания платит.',
      farsi: 'اشکالی ندارد. من در سفر کاری هستم و شرکت هزینه را پرداخت می‌کند.',
    },
    {
      sentence: 'Dann brauche ich auch noch ein Hotel. Es soll im Stadtzentrum liegen.',
      english: 'Then I also need a hotel. It should be in the city center.',
      russian: 'Тогда мне также нужен отель. Он должен находиться в центре города.',
      farsi: 'سپس من یک هتل هم نیاز دارم. باید در مرکز شهر باشد.',
    },
    {
      sentence: 'Gerne. Da gibt es zum Beispiel das Hotel Metropol.',
      english: 'Sure. There is, for example, the Hotel Metropol.',
      russian: 'Конечно. Например, есть отель Метрополь.',
      farsi: 'البته. به عنوان مثال، هتل متروپول وجود دارد.',
    },
    {
      sentence: 'Soll ich die Buchung machen?',
      english: 'Shall I make the booking?',
      russian: 'Мне оформить бронь?',
      farsi: 'آیا باید رزرو کنم؟',
    },
    {
      sentence: 'Ja, bitte. Mein Name ist Kerstin Bloch und meine Adresse ist ...',
      english: 'Yes, please. My name is Kerstin Bloch and my address is ...',
      russian: 'Да, пожалуйста. Меня зовут Керстин Блох, и мой адрес ...',
      farsi: 'بله، لطفا. نام من کرستین بلوخ است و آدرس من ...',
    },
    {
      sentence: 'Oh bitte noch einmal etwas langsamer. Ich muss alles in den Computer eingeben.',
      english: 'Oh please, a bit slower. I have to enter everything into the computer.',
      russian: 'О, пожалуйста, немного помедленнее. Мне нужно ввести все в компьютер.',
      farsi: 'اوه لطفا کمی آهسته‌تر. من باید همه چیز را وارد کامپیوتر کنم.',
    },
    {
      sentence: 'Guten Tag, nehmen Sie doch bitte Platz.',
      english: 'Good day, please take a seat.',
      russian: 'Добрый день, пожалуйста, присаживайтесь.',
      farsi: 'روز بخیر، لطفاً بنشینید.',
    },
    {
      sentence: 'Was kann ich für Sie tun?',
      english: 'What can I do for you?',
      russian: 'Чем я могу вам помочь?',
      farsi: 'چه کاری می‌توانم برای شما انجام دهم؟',
    },
    {
      sentence: 'Guten Tag. Ich möchte eine Reise für zwei Personen in die Türkei buchen.',
      english: 'Good day. I want to book a trip for two people to Turkey.',
      russian: 'Добрый день. Я хочу забронировать поездку на двоих в Турцию.',
      farsi: 'روز بخیر. می‌خواهم یک سفر برای دو نفر به ترکیه رزرو کنم.',
    },
    {
      sentence: 'Wann wollen Sie reisen?',
      english: 'When do you want to travel?',
      russian: 'Когда вы хотите путешествовать?',
      farsi: 'کی می‌خواهید سفر کنید؟',
    },
    {
      sentence: 'Meine Frau und ich wollen im Sommer Urlaub machen.',
      english: 'My wife and I want to go on vacation in the summer.',
      russian: 'Моя жена и я хотим поехать в отпуск летом.',
      farsi: 'من و همسرم می‌خواهیم در تابستان به تعطیلات برویم.',
    },
    {
      sentence: 'Wir suchen eine kleine Ferienwohnung, die am Meer liegt.',
      english: 'We are looking for a small holiday apartment by the sea.',
      russian: 'Мы ищем маленькую квартиру для отдыха у моря.',
      farsi: 'ما دنبال یک آپارتمان کوچک برای تعطیلات در کنار دریا هستیم.',
    },
    {
      sentence: 'Wir wollen zwei Wochen bleiben.',
      english: 'We want to stay for two weeks.',
      russian: 'Мы хотим остаться на две недели.',
      farsi: 'ما می‌خواهیم دو هفته بمانیم.',
    },
    {
      sentence: 'Ich habe hier einen Katalog mit Angeboten, die sehr günstig sind.',
      english: 'I have here a catalog with offers that are very affordable.',
      russian: 'У меня есть каталог с предложениями, которые очень выгодны.',
      farsi: 'من اینجا یک کاتالوگ با پیشنهادات بسیار مقرون به صرفه دارم.',
    },
    {
      sentence: 'Ich empfehle Ihnen Antalya. Hier sind einige Fotos mit Ferienwohnungen am Meer.',
      english: 'I recommend Antalya. Here are some photos of holiday apartments by the sea.',
      russian: 'Я рекомендую Анталью. Вот несколько фотографий квартир для отдыха у моря.',
      farsi: 'من آنتالیا را توصیه می‌کنم. اینجا چند عکس از آپارتمان‌های تعطیلاتی در کنار دریا هست.',
    },
    {
      sentence: 'Darf ich mal sehen?',
      english: 'May I take a look?',
      russian: 'Можно мне посмотреть?',
      farsi: 'می‌توانم ببینم؟',
    },
    {
      sentence: 'Ja, die Fotos sind sehr schön und diese Wohnung gefällt mir sehr gut.',
      english: 'Yes, the photos are very nice and I really like this apartment.',
      russian: 'Да, фотографии очень красивые, и эта квартира мне очень нравится.',
      farsi: 'بله، عکس‌ها خیلی زیبا هستند و من این آپارتمان را خیلی دوست دارم.',
    },
    {
      sentence: 'Wie ist es mit den Flügen?',
      english: 'How about the flights?',
      russian: 'Как насчет рейсов?',
      farsi: 'پروازها چطور هستند؟',
    },
    {
      sentence: 'Hier habe ich einen Flug: Sie fliegen am 24. Juli von Frankfurt ab.',
      english: 'Here I have a flight: You fly on July 24th from Frankfurt.',
      russian: 'Вот у меня есть рейс: Вы вылетаете 24 июля из Франкфурта.',
      farsi: 'اینجا یک پرواز دارم: شما در 24 ژوئیه از فرانکفورت پرواز می‌کنید.',
    },
    {
      sentence:
        'Der Rückflug ist dann am 7. August. Flug und Ferienwohnung kosten zusammen 980 Euro für zwei Personen.',
      english:
        'The return flight is on August 7th. Flight and holiday apartment together cost 980 euros for two people.',
      russian: 'Обратный рейс 7 августа. Полет и квартира для отдыха вместе стоят 980 евро на двоих.',
      farsi: 'پرواز برگشت در 7 اوت است. پرواز و آپارتمان تعطیلاتی برای دو نفر با هم 980 یورو هزینه دارند.',
    },
    {
      sentence: 'Das klingt gut, die Reise nehme ich.',
      english: "That sounds good, I'll take the trip.",
      russian: 'Звучит хорошо, я беру эту поездку.',
      farsi: 'این خوب به نظر می‌رسد، من این سفر را می‌خواهم.',
    },
    {
      sentence: 'Braucht man für die Türkei eigentlich ein Visum?',
      english: 'Do you actually need a visa for Turkey?',
      russian: 'На самом деле, нужен ли вам виз для Турции?',
      farsi: 'آیا برای ترکیه واقعاً ویزا نیاز است؟',
    },
    {
      sentence:
        'Als Deutscher brauchen Sie nur einen Reisepass oder einen Ausweis, der noch drei Monate gültig ist, aber kein Visum.',
      english: 'As a German, you only need a passport or an ID card that is still valid for three months, but no visa.',
      russian:
        'Как гражданин Германии, вам нужен только паспорт или удостоверение личности, действительное еще три месяца, но не виза.',
      farsi: 'به عنوان یک آلمانی، فقط به گذرنامه یا کارت شناسایی که هنوز سه ماه معتبر است، اما به ویزا نیاز ندارید.',
    },
    {
      sentence: 'Dann können wir also mit den Pässen ohne Visum fliegen?',
      english: 'So we can fly with passports without a visa?',
      russian: 'Значит, мы можем лететь с паспортами без визы?',
      farsi: 'پس می‌توانیم با گذرنامه بدون ویزا پرواز کنیم؟',
    },
    {
      sentence: 'Ja, so ist es.',
      english: "Yes, that's right.",
      russian: 'Да, это так.',
      farsi: 'بله، همینطور است.',
    },
    {
      sentence: 'Notrufzentrale, was kann ich für Sie tun?',
      english: 'Emergency center, what can I do for you?',
      russian: 'Центр экстренной помощи, чем я могу вам помочь?',
      farsi: 'مرکز اورژانس، چه کاری می‌توانم برای شما انجام دهم؟',
    },
    {
      sentence: 'Hallo, hier spricht Horvat. Ich bin auf der Al Richtung Köln. Ich habe eine Autopanne.',
      english: "Hello, this is Horvat speaking. I'm on the A1 towards Cologne. I have a car breakdown.",
      russian: 'Здравствуйте, говорит Хорват. Я на A1 в сторону Кёльна. У меня поломка машины.',
      farsi: 'سلام، اینجا هوروات صحبت می‌کند. من در جاده A1 به سمت کلن هستم. ماشینم خراب شده.',
    },
    {
      sentence: 'Wo sind Sie genau?',
      english: 'Where exactly are you?',
      russian: 'Где вы точно находитесь?',
      farsi: 'دقیقاً کجا هستید؟',
    },
    {
      sentence: 'Hier auf der Notrufsäule steht Kilometer 166,5. Mein Auto ist kurz vor der Säule.',
      english: 'Here on the emergency phone stands kilometer 166.5. My car is just before the pole.',
      russian: 'Здесь на аварийной колонке указано 166,5 километра. Моя машина чуть перед колонкой.',
      farsi: 'اینجا روی ستون اورژانس نوشته شده کیلومتر 166.5. ماشینم درست قبل از ستون است.',
    },
    {
      sentence: 'Wir schicken den Pannendienst.',
      english: 'We are sending the breakdown service.',
      russian: 'Мы отправляем службу помощи на дороге.',
      farsi: 'ما خدمات امداد جاده‌ای را می‌فرستیم.',
    },
    {
      sentence: 'Entschuldigen Sie bitte, ich glaube, Sie sitzen auf meinem Platz. Wagen 7, Platz 41.',
      english: 'Excuse me, I think you are sitting in my seat. Car 7, seat 41.',
      russian: 'Извините, мне кажется, вы сидите на моем месте. Вагон 7, место 41.',
      farsi: 'ببخشید، فکر می‌کنم شما روی صندلی من نشسته‌اید. واگن 7، صندلی 41.',
    },
    {
      sentence: 'Ich habe auch eine Reservierung für Platz 41 …Oh, aber in Wagen 6! Tut mir leid!',
      english: 'I also have a reservation for seat 41 ... Oh, but in car 6! Sorry!',
      russian: 'У меня тоже есть бронь на место 41 ... О, но в вагоне 6! Простите!',
      farsi: 'من هم برای صندلی 41 رزرو دارم ... اوه، اما در واگن 6! ببخشید!',
    },
    {
      sentence: 'Das macht nichts. Das ist mir auch schon passiert.',
      english: "That's okay. That has happened to me too.",
      russian: 'Ничего страшного. Это тоже со мной случалось.',
      farsi: 'اشکالی ندارد. این برای من هم اتفاق افتاده است.',
    },
    {
      sentence: 'Kennen Sie eine Sprachschule, die Deutschkurse anbietet?',
      english: 'Do you know a language school that offers German courses?',
      russian: 'Вы знаете языковую школу, которая предлагает курсы немецкого?',
      farsi: 'آیا یک مدرسه زبان می‌شناسید که دوره‌های آلمانی ارائه دهد؟',
    },
    {
      sentence: 'Kennen Sie ein Café, das auch Internet hat?',
      english: 'Do you know a café that also has internet?',
      russian: 'Вы знаете кафе, в котором есть интернет?',
      farsi: 'آیا یک کافه می‌شناسید که اینترنت هم داشته باشد؟',
    },
    {
      sentence: 'Kennen Sie einen Kindergarten, der in der Nähe ist?',
      english: 'Do you know a kindergarten that is nearby?',
      russian: 'Вы знаете детский сад, который находится поблизости?',
      farsi: 'آیا یک مهدکودک می‌شناسید که در نزدیکی باشد؟',
    },
    {
      sentence: 'Kennen Sie eine Schule, die Russisch anbietet?',
      english: 'Do you know a school that offers Russian?',
      russian: 'Вы знаете школу, которая предлагает уроки русского языка?',
      farsi: 'آیا یک مدرسه می‌شناسید که روسی ارائه دهد؟',
    },
    {
      sentence: 'Kennen Sie ein Geschäft, das immer frisches Gemüse hat?',
      english: 'Do you know a store that always has fresh vegetables?',
      russian: 'Вы знаете магазин, который всегда имеет свежие овощи?',
      farsi: 'آیا یک فروشگاه می‌شناسید که همیشه سبزیجات تازه داشته باشد؟',
    },
    {
      sentence: 'Kennen Sie ein Restaurant, das türkische Spezialitäten anbietet?',
      english: 'Do you know a restaurant that offers Turkish specialties?',
      russian: 'Вы знаете ресторан, который предлагает турецкие деликатесы?',
      farsi: 'آیا یک رستوران می‌شناسید که غذاهای ویژه ترکی ارائه دهد؟',
    },
  ],
};
export default deutschSentences_a2_u11;
