const startLesson = {
  info: {
    name: 'Start_Lesson',
    learning: 'Sentences',
  },

  content: [
    {
      isSelected: false,
      type: 'sentence',
      sentence: 'Herzlich willkommen bei Abri Lingo! ',
      english: 'Welcome to Abri Lingo!',
      russian: 'Добро пожаловать в Абри Линго!',
      farsi: 'به Abri Lingo خوش آمدید!',
    },
  ],
};

const noSentenceSelected = {
  info: {
    name: 'No_Sentence_Selected',
    learning: 'Sentences',
  },

  content: [
    {
      isSelected: false,
      type: 'sentence',
      sentence: 'Es ist kein Satz ausgewählt.! ',
      english: 'There are no selected sentences.!',
      russian: 'Нет выбранного предложения.!',
      farsi: 'هیچ جمله انتخابی وجود ندارد!',
    },
  ],
};

const alllessons = [
  {
    id: '100',
    name: 'Prüfung B 1',
    level: 0,
    children: [
      {
        id: '101',
        level: 1,
        file_name: 'b1_sprechen_teil_1.json',
        name: 'B1 Sprechen Teil 1',
      },
      {
        id: '102',
        level: 1,
        file_name: 'b1_sprechen_teil_2.json',
        name: 'B1 Sprechen Teil 2',
      },
    ],
  },
  {
    id: '200',
    name: 'Verben',
    level: 0,
    children: [
      {
        id: '201',
        level: 1,
        file_name: 'a1_unregelmäßige_verben.json',
        name: 'A1 Unregelmäßige Verben',
      },
      {
        id: '202',
        level: 1,
        file_name: 'a1_unregelmäßige_verben_sentence.json',
        name: 'A1 Unregelmäßige Verben Sentence',
      },
      {
        id: '203',
        level: 1,
        file_name: 'a1_regelmäßige_verben.json',
        name: 'A1 Regelmäßige Verben',
      },
      {
        id: '204',
        level: 1,
        file_name: 'a1_regelmäßige_verben_sentence.json',
        name: 'A1 Regelmäßige Verben Sentence',
      },
      {
        id: '205',
        level: 1,
        file_name: 'a2_unregelmäßige_verben.json',
        name: 'A2 Unregelmäßige Verben',
      },
      {
        id: '206',
        level: 1,
        file_name: 'a2_unregelmäßige_verben_sentence.json',
        name: 'A2 Unregelmäßige Verben Sentence',
      },
      {
        id: '207',
        level: 1,
        file_name: 'a2_regelmäßige_verben.json',
        name: 'A2 Regelmäßige Verben',
      },
      {
        id: '208',
        level: 1,
        file_name: 'a2_regelmäßige_verben_sentence.json',
        name: 'A2 Regelmäßige Verben Sentence',
      },
      {
        id: '209',
        level: 1,
        file_name: 'fokus_b1_verben.json',
        name: 'Fokus B1 Verben',
      },
      {
        id: '210',
        level: 1,
        file_name: 'modalverben.json',
        name: 'Modalverben',
      },
      {
        id: '211',
        level: 1,
        file_name: 'verben_mit_präposition_akkusativ.json',
        name: 'Verben mit Präposition Akkusativ',
      },
      {
        id: '212',
        level: 1,
        file_name: 'verben_mit_präposition_dativ.json',
        name: 'Verben mit Präposition Dativ',
      },
      {
        id: '213',
        level: 1,
        file_name: 'verben_mit_dativ_und_akkusativ.json',
        name: 'Verben Mit Dativ Und Akkusativ',
      },
      {
        id: '214',
        level: 1,
        file_name: 'verben_mit_dativ.json',
        name: 'Verben Mit Dativ',
      },
      {
        id: '215',
        level: 1,
        file_name: '200_wichtigsten_verben.json',
        name: '200 Wichtigsten Verben',
      },
      {
        id: '216',
        level: 1,
        file_name: 'grundlegende_unregelmäßige_verben.json',
        name: 'Grundlegende Unregelmäßige Verben',
      },
    ],
  },
  {
    id: '300',
    name: 'B1_Fokus',
    level: 0,
    children: [
      {
        id: '332',
        level: 1,
        file_name: 'b1_fokus_wörter_u01.json',
        name: 'B1 Fokus Wörter U01',
      },
      {
        id: '301',
        level: 1,
        file_name: 'b1_fokus_u01.json',
        name: 'B1 Fokus U01',
      },
      {
        id: '333',
        level: 1,
        file_name: 'b1_fokus_wörter_u02.json',
        name: 'B1 Fokus Wörter U02',
      },
      {
        id: '302',
        level: 1,
        file_name: 'b1_fokus_u02.json',
        name: 'B1 Fokus U02',
      },
      {
        id: '334',
        level: 1,
        file_name: 'b1_fokus_wörter_u03.json',
        name: 'B1 Fokus Wörter U03',
      },
      {
        id: '303',
        level: 1,
        file_name: 'b1_fokus_u03.json',
        name: 'B1 Fokus U03',
      },
      {
        id: '335',
        level: 1,
        file_name: 'b1_fokus_wörter_u04.json',
        name: 'B1 Fokus Wörter U04',
      },
      {
        id: '304',
        level: 1,
        file_name: 'b1_fokus_u04.json',
        name: 'B1 Fokus U04',
      },
      {
        id: '336',
        level: 1,
        file_name: 'b1_fokus_wörter_u05.json',
        name: 'B1 Fokus Wörter U05',
      },
      {
        id: '305',
        level: 1,
        file_name: 'b1_fokus_u05.json',
        name: 'B1 Fokus U05',
      },
      {
        id: '337',
        level: 1,
        file_name: 'b1_fokus_wörter_u06.json',
        name: 'B1 Fokus Wörter U06',
      },
      {
        id: '306',
        level: 1,
        file_name: 'b1_fokus_u06.json',
        name: 'B1 Fokus U06',
      },
      {
        id: '338',
        level: 1,
        file_name: 'b1_fokus_wörter_u07.json',
        name: 'B1 Fokus Wörter U07',
      },
      {
        id: '307',
        level: 1,
        file_name: 'b1_fokus_u07.json',
        name: 'B1 Fokus U07',
      },
      {
        id: '339',
        level: 1,
        file_name: 'b1_fokus_wörter_u08.json',
        name: 'B1 Fokus Wörter U08',
      },
      {
        id: '308',
        level: 1,
        file_name: 'b1_fokus_u08.json',
        name: 'B1 Fokus U08',
      },
      {
        id: '340',
        level: 1,
        file_name: 'b1_fokus_wörter_u09.json',
        name: 'B1 Fokus Wörter U09',
      },
      {
        id: '310',
        level: 1,
        file_name: 'b1_fokus_u09.json',
        name: 'B1 Fokus U09',
      },
      {
        id: '341',
        level: 1,
        file_name: 'b1_fokus_wörter_u10.json',
        name: 'B1 Fokus Wörter U10',
      },
      {
        id: '311',
        level: 1,
        file_name: 'b1_fokus_u10.json',
        name: 'B1 Fokus U10',
      },
      {
        id: '342',
        level: 1,
        file_name: 'b1_fokus_wörter_u11.json',
        name: 'B1 Fokus Wörter U11',
      },
      {
        id: '332',
        level: 1,
        file_name: 'b1_fokus_u11.json',
        name: 'B1 Fokus U11',
      },
      {
        id: '343',
        level: 1,
        file_name: 'b1_fokus_wörter_u12.json',
        name: 'B1 Fokus Wörter U12',
      },
      {
        id: '344',
        level: 1,
        file_name: 'b1_fokus_u12.json',
        name: 'B1 Fokus U12',
      },
      {
        id: '345',
        level: 1,
        file_name: 'b1_fokus_wörter_u13.json',
        name: 'B1 Fokus Wörter U13',
      },
      {
        id: '346',
        level: 1,
        file_name: 'b1_fokus_u13.json',
        name: 'B1 Fokus U13',
      },
      {
        id: '347',
        level: 1,
        file_name: 'b1_fokus_wörter_u14.json',
        name: 'B1 Fokus Wörter U14',
      },
      {
        id: '348',
        level: 1,
        file_name: 'b1_fokus_u14.json',
        name: 'B1 Fokus U14',
      },
      {
        id: '309',
        level: 1,
        file_name: 'verben_mit_präposition_fokus_b1.json',
        name: 'Verben Mit Präposition Fokus B1',
      },
      {
        id: '209',
        level: 1,
        file_name: 'fokus_b1_verben.json',
        name: 'Fokus B1 Verben',
      },
    ],
  },
  {
    id: '1100',
    name: 'B1+_Fokus',
    level: 0,
    children: [
      {
        id: '1101',
        level: 1,
        file_name: 'b1_plus_fokus_wörter_01.json',
        name: 'B1+ Fokus Wörter 01',
      },
      {
        id: '1102',
        level: 1,
        file_name: 'b1_plus_fokus_01.json',
        name: 'B1+ Fokus 01',
      },
      {
        id: '1103',
        level: 1,
        file_name: 'b1_plus_fokus_wörter_02.json',
        name: 'B1+ Fokus Wörter 02',
      },
      {
        id: '1104',
        level: 1,
        file_name: 'b1_plus_fokus_02.json',
        name: 'B1+ Fokus 02',
      },
    ],
  },
  {
    id: '900',
    name: 'Wortliste',
    level: 0,
    children: [
      {
        id: '910',
        name: 'A1_Wortliste',
        level: 1,
        children: [
          {
            id: '901',
            level: 1,
            file_name: 'a1_wortliste_01.json',
            name: 'A1 Wortliste 01',
          },
          {
            id: '902',
            level: 1,
            file_name: 'a1_wortliste_02.json',
            name: 'A1 Wortliste 02',
          },
          {
            id: '903',
            level: 1,
            file_name: 'a1_wortliste_03.json',
            name: 'A1 Wortliste 03',
          },
          {
            id: '904',
            level: 1,
            file_name: 'a1_wortliste_04.json',
            name: 'A1 Wortliste 04',
          },
          {
            id: '905',
            level: 1,
            file_name: 'a1_wortliste_05.json',
            name: 'A1 Wortliste 05',
          },
          {
            id: '906',
            level: 1,
            file_name: 'a1_wortliste_06.json',
            name: 'A1 Wortliste 06',
          },
        ],
      },
      {
        id: '930',
        name: 'B1_Wortliste',
        level: 1,
        children: [
          {
            id: '931',
            level: 1,
            file_name: 'b1_wortliste_01.json',
            name: 'B1 Wortliste 01',
          },
          {
            id: '932',
            level: 1,
            file_name: 'b1_wortliste_02.json',
            name: 'B1 Wortliste 02',
          },
          {
            id: '933',
            level: 1,
            file_name: 'b1_wortliste_03.json',
            name: 'B1 Wortliste 03',
          },
          {
            id: '934',
            level: 1,
            file_name: 'b1_wortliste_04.json',
            name: 'B1 Wortliste 04',
          },
          {
            id: '935',
            level: 1,
            file_name: 'b1_wortliste_05.json',
            name: 'B1 Wortliste 05',
          },
          {
            id: '936',
            level: 1,
            file_name: 'b1_wortliste_06.json',
            name: 'B1 Wortliste 06',
          },
        ],
      },
    ],
  },
  {
    id: '400',
    name: 'Gespräch',
    level: 0,
    children: [
      {
        id: '401',
        level: 1,
        file_name: 'nützliche_sätze.json',
        name: 'Nützliche Sätze',
      },
      {
        id: '402',
        level: 1,
        file_name: 'im_supermarkt.json',
        name: 'Im Supermarkt',
      },
      {
        id: '403',
        level: 1,
        file_name: 'essen.json',
        name: 'Essen',
      },
      {
        id: '404',
        level: 1,
        file_name: 'adresse.json',
        name: 'Adresse',
      },
    ],
  },
  {
    id: '500',
    name: 'Grammatik',
    level: 0,
    children: [
      {
        id: '501',
        level: 1,
        file_name: 'alle_konjunktionen.json',
        name: 'Alle Konjunktionen',
      },
      {
        id: '502',
        level: 1,
        file_name: 'lokale_präpositionen_mit_akk.json',
        name: 'Lokale Präpositionen Mit Akk.',
      },
      {
        id: '505',
        level: 1,
        file_name: 'lokale_präpositionen_mit_dat.json',
        name: 'Lokale Präpositionen Mit Dat.',
      },
      {
        id: '506',
        level: 1,
        file_name: 'lokale_präpositionen_mit_dat_akk.json',
        name: 'Lokale Präpositionen Mit Dat. Akk.',
      },
      {
        id: '503',
        level: 1,
        file_name: 'temporale_präpositionen.json',
        name: 'Temporale Präpositionen',
      },
      {
        id: '504',
        level: 1,
        file_name: 'zu_infinitiv.json',
        name: 'Zu Infinitiv',
      },
    ],
  },
  {
    id: '600',
    name: 'Pluspunkt',
    level: 0,
    children: [
      {
        id: '601',
        name: 'Pluspunkt_A1',
        level: 1,
        children: [
          {
            id: '601_01',
            level: 2,
            file_name: 'a1_u01.json',
            name: 'A1U01',
          },
          {
            id: '601_02',
            level: 2,
            file_name: 'a1_u02.json',
            name: 'A1U02',
          },
          {
            id: '601_03',
            level: 2,
            file_name: 'a1_u03.json',
            name: 'A1U03',
          },
          {
            id: '601_04',
            level: 2,
            file_name: 'a1_u04.json',
            name: 'A1U04',
          },
          {
            id: '601_05',
            level: 2,
            file_name: 'a1_u05.json',
            name: 'A1U06',
          },
          {
            id: '601_06',
            level: 2,
            file_name: 'a1_u06.json',
            name: 'A1U06',
          },
          {
            id: '601_07',
            level: 2,
            file_name: 'a1_u07.json',
            name: 'A1U07',
          },
          {
            id: '601_08',
            level: 2,
            file_name: 'a1_u08.json',
            name: 'A1U08',
          },
          {
            id: '601_09',
            level: 2,
            file_name: 'a1_u09.json',
            name: 'A1U09',
          },
          {
            id: '601_10',
            level: 2,
            file_name: 'a1_u10.json',
            name: 'A1U10',
          },
          {
            id: '601_11',
            level: 2,
            file_name: 'a1_u11.json',
            name: 'A1U11',
          },
          {
            id: '601_12',
            level: 2,
            file_name: 'a1_u12.json',
            name: 'A1U12',
          },
          {
            id: '601_13',
            level: 2,
            file_name: 'a1_u13.json',
            name: 'A1U13',
          },
          {
            id: '601_14',
            level: 2,
            file_name: 'a1_u14.json',
            name: 'A1U14',
          },
        ],
      },
      {
        id: '602',
        name: 'Pluspunkt_A2',
        level: 1,
        children: [
          {
            id: '602_01',
            level: 2,
            file_name: 'a2_u01.json',
            name: 'A2U01',
          },
          {
            id: '602_02',
            level: 2,
            file_name: 'a2_u02.json',
            name: 'A2U02',
          },
          {
            id: '602_03',
            level: 2,
            file_name: 'a2_u03.json',
            name: 'A2U03',
          },
          {
            id: '602_04',
            level: 2,
            file_name: 'a2_u04.json',
            name: 'A2U04',
          },
          {
            id: '602_s1',
            level: 2,
            file_name: 'a2_s1.json',
            name: 'A2S1',
          },
          {
            id: '602_05',
            level: 2,
            file_name: 'a2_u05.json',
            name: 'A2U05',
          },
          {
            id: '602_06',
            level: 2,
            file_name: 'a2_u06.json',
            name: 'A2U06',
          },
          {
            id: '602_07',
            level: 2,
            file_name: 'a2_u07.json',
            name: 'A2U07',
          },
          {
            id: '602_s2',
            level: 2,
            file_name: 'a2_s2.json',
            name: 'A2S2',
          },
          {
            id: '602_08',
            level: 2,
            file_name: 'a2_u08.json',
            name: 'A2U08',
          },
          {
            id: '602_09',
            level: 2,
            file_name: 'a2_u09.json',
            name: 'A2U09',
          },
          {
            id: '602_10',
            level: 2,
            file_name: 'a2_u10.json',
            name: 'A2U10',
          },
          {
            id: '602_11',
            level: 2,
            file_name: 'a2_u11.json',
            name: 'A2U11',
          },
          {
            id: '602_s3',
            level: 2,
            file_name: 'a2_s3.json',
            name: 'A2S3',
          },
          {
            id: '602_12',
            level: 2,
            file_name: 'a2_u12.json',
            name: 'A2U12',
          },
          {
            id: '602_13',
            level: 2,
            file_name: 'a2_u13.json',
            name: 'A2U13',
          },
          { id: '602_14', level: 2, file_name: 'a2_u14.json', name: 'A2U14' },
          {
            id: '602_s4',
            level: 2,
            file_name: 'a2_s4.json',
            name: 'A2S4',
          },
        ],
      },
      {
        id: '603',
        name: 'Pluspunkt_B1',
        level: 1,
        children: [
          {
            id: '603_01',
            level: 2,
            file_name: 'b1_u01.json',
            name: 'B1U01',
          },
          {
            id: '603_02',
            level: 2,
            file_name: 'b1_u02.json',
            name: 'B1U02',
          },
          {
            id: '603_03',
            level: 2,
            file_name: 'b1_u03.json',
            name: 'B1U03',
          },
          {
            id: '603_04',
            level: 2,
            file_name: 'b1_u04.json',
            name: 'B1U04',
          },
          {
            id: '603_05',
            level: 2,
            file_name: 'b1_u05.json',
            name: 'B1U05',
          },
          {
            id: '603_06',
            level: 2,
            file_name: 'b1_u06.json',
            name: 'B1U06',
          },
        ],
      },
    ],
  },
  {
    id: '700',
    name: 'Frontend & Backend',
    level: 0,
    children: [
      {
        id: '701',
        level: 1,
        file_name: 'frontend_backend_01.json',
        name: 'Frontend Backend 01',
      },
      {
        id: '702',
        level: 1,
        file_name: 'frontend_backend_02.json',
        name: 'Frontend Backend 02',
      },
      {
        id: '703',
        level: 1,
        file_name: 'frontend_backend_03.json',
        name: 'Frontend Backend 03',
      },
      {
        id: '704',
        level: 1,
        file_name: 'frontend_backend_04.json',
        name: 'Frontend Backend 04',
      },
      {
        id: '705',
        level: 1,
        file_name: 'frontend_backend_05.json',
        name: 'Frontend Backend 05',
      },
      {
        id: '706',
        level: 1,
        file_name: 'frontend_backend_06.json',
        name: 'Frontend Backend 06',
      },
      {
        id: '707',
        level: 1,
        file_name: 'frontend_1_100.json',
        name: 'Frontend 1_100',
      },
      {
        id: '708',
        level: 1,
        file_name: 'frontend_100_200.json',
        name: 'Frontend 100_200',
      },
    ],
  },
  {
    id: '1000',
    name: 'Mein Mündliche Prüfung Teil 1(Beruf B1)',
    level: 0,
    children: [
      {
        id: '1001',
        level: 1,
        file_name: '1_beschreiben_sie_einen_arbeitgeber.json',
        name: '1 Beschreiben Sie einen Arbeitgeber',
      },
      {
        id: '1002',
        level: 1,
        file_name: '2_beschreiben_sie_einen_bestimmten_Beruf.json',
        name: '2 Beschreiben Sie einen bestimmten Beruf',
      },
    ],
  },
  {
    id: '800',
    name: 'test',
    level: 0,
    children: [
      {
        id: '801',
        level: 0,
        file_name: 'quiz_1.json',
        name: 'Quiz_1',
      },
    ],
  },
];
const allLanguagesTranslate = ['english', 'russian', 'farsi'];

export { alllessons, allLanguagesTranslate, startLesson, noSentenceSelected };
