const verben_02 = {
  info: {
    name: 'Verben_02',
    learning: 'Sentences',
  },

  content: [
    {
      sentence: 'Ich habe einen Hund.',
      english: 'I have a dog.',
      russian: 'У меня есть собака.',
      farsi: 'من یک سگ دارم.',
    },
    {
      sentence: 'Er hat ein Auto.',
      english: 'He has a car.',
      russian: 'У него есть машина.',
      farsi: 'او یک ماشین دارد.',
    },
    {
      sentence: 'Wir haben ein Haus.',
      english: 'We have a house.',
      russian: 'У нас есть дом.',
      farsi: 'ما یک خانه داریم.',
    },
    {
      sentence: 'Sie haben eine Katze.',
      english: 'They have a cat.',
      russian: 'У них есть кошка.',
      farsi: 'آنها یک گربه دارند.',
    },
    {
      sentence: 'Hast du Geschwister?',
      english: 'Do you have siblings?',
      russian: 'У тебя есть братья и сестры?',
      farsi: 'آیا خواهر و برادر داری؟',
    },
    {
      sentence: 'Ich habe zwei Brüder.',
      english: 'I have two brothers.',
      russian: 'У меня два брата.',
      farsi: 'من دو برادر دارم.',
    },
    {
      sentence: 'Wir haben einen Garten.',
      english: 'We have a garden.',
      russian: 'У нас есть сад.',
      farsi: 'ما یک باغ داریم.',
    },
    {
      sentence: 'Er hat viele Freunde.',
      english: 'He has many friends.',
      russian: 'У него много друзей.',
      farsi: 'او دوستان زیادی دارد.',
    },
    {
      sentence: 'Sie hat ein schönes Kleid.',
      english: 'She has a beautiful dress.',
      russian: 'У нее красивое платье.',
      farsi: 'او یک لباس زیبا دارد.',
    },
    {
      sentence: 'Wir haben einen Plan.',
      english: 'We have a plan.',
      russian: 'У нас есть план.',
      farsi: 'ما یک برنامه داریم.',
    },
    {
      sentence: 'Ich habe gestern ein Buch gekauft.',
      english: 'I bought a book yesterday.',
      russian: 'Я купил книгу вчера.',
      farsi: 'من دیروز یک کتاب خریدم.',
    },
    {
      sentence: 'Er hat letzte Woche Geburtstag gehabt.',
      english: 'He had a birthday last week.',
      russian: 'У него был день рождения на прошлой неделе.',
      farsi: 'او هفته گذشته تولد داشت.',
    },
    {
      sentence: 'Wir haben einen schönen Urlaub gehabt.',
      english: 'We had a nice vacation.',
      russian: 'У нас был хороший отпуск.',
      farsi: 'ما یک تعطیلات خوب داشتیم.',
    },
    {
      sentence: 'Sie haben viel Spaß gehabt.',
      english: 'They had a lot of fun.',
      russian: 'Они хорошо повеселились.',
      farsi: 'آنها خیلی خوش گذراندند.',
    },
    {
      sentence: 'Hattest du eine gute Zeit?',
      english: 'Did you have a good time?',
      russian: 'Ты хорошо провел время?',
      farsi: 'آیا بهت خوش گذشت؟',
    },
    {
      sentence: 'Ich habe einen langen Tag gehabt.',
      english: 'I had a long day.',
      russian: 'У меня был длинный день.',
      farsi: 'من یک روز طولانی داشتم.',
    },
    {
      sentence: 'Wir haben ein interessantes Gespräch gehabt.',
      english: 'We had an interesting conversation.',
      russian: 'У нас был интересный разговор.',
      farsi: 'ما یک گفتگوی جالب داشتیم.',
    },
    {
      sentence: 'Er hat eine gute Idee gehabt.',
      english: 'He had a good idea.',
      russian: 'У него была хорошая идея.',
      farsi: 'او یک ایده خوب داشت.',
    },
    {
      sentence: 'Sie hat ein schönes Wochenende gehabt.',
      english: 'She had a nice weekend.',
      russian: 'У нее были хорошие выходные.',
      farsi: 'او یک آخر هفته خوب داشت.',
    },
    {
      sentence: 'Ich habe letzte Nacht einen Traum gehabt.',
      english: 'I had a dream last night.',
      russian: 'У меня был сон прошлой ночью.',
      farsi: 'من دیشب یک رویا داشتم.',
    },
    {
      sentence: 'Ich werde morgen frei haben.',
      english: 'I will have a day off tomorrow.',
      russian: 'Завтра у меня будет выходной.',
      farsi: 'من فردا تعطیل خواهم بود.',
    },
    {
      sentence: 'Er wird nächste Woche Urlaub haben.',
      english: 'He will have a vacation next week.',
      russian: 'На следующей неделе у него будет отпуск.',
      farsi: 'او هفته آینده تعطیلات خواهد داشت.',
    },
    {
      sentence: 'Wir werden bald ein Treffen haben.',
      english: 'We will have a meeting soon.',
      russian: 'Скоро у нас будет встреча.',
      farsi: 'ما به زودی یک جلسه خواهیم داشت.',
    },
    {
      sentence: 'Sie werden viele Gäste haben.',
      english: 'They will have many guests.',
      russian: 'У них будет много гостей.',
      farsi: 'آنها مهمانان زیادی خواهند داشت.',
    },
    {
      sentence: 'Wirst du Zeit haben?',
      english: 'Will you have time?',
      russian: 'У тебя будет время?',
      farsi: 'آیا وقت خواهی داشت؟',
    },
    {
      sentence: 'Ich werde eine Prüfung haben.',
      english: 'I will have an exam.',
      russian: 'У меня будет экзамен.',
      farsi: 'من یک امتحان خواهم داشت.',
    },
    {
      sentence: 'Wir werden eine Party haben.',
      english: 'We will have a party.',
      russian: 'У нас будет вечеринка.',
      farsi: 'ما یک مهمانی خواهیم داشت.',
    },
    {
      sentence: 'Er wird morgen eine Besprechung haben.',
      english: 'He will have a meeting tomorrow.',
      russian: 'Завтра у него будет собрание.',
      farsi: 'او فردا یک جلسه خواهد داشت.',
    },
    {
      sentence: 'Sie wird bald ein Baby haben.',
      english: 'She will have a baby soon.',
      russian: 'У нее скоро будет ребенок.',
      farsi: 'او به زودی یک بچه خواهد داشت.',
    },
    {
      sentence: 'Ich werde nächste Woche eine Überraschung haben.',
      english: 'I will have a surprise next week.',
      russian: 'На следующей неделе у меня будет сюрприз.',
      farsi: 'من هفته آینده یک سورپرایز خواهم داشت.',
    },
    {
      sentence: 'Ich kenne ihn.',
      english: 'I know him.',
      russian: 'Я знаю его.',
      farsi: 'من او را می‌شناسم.',
    },
    {
      sentence: 'Er kennt sie.',
      english: 'He knows her.',
      russian: 'Он знает её.',
      farsi: 'او او را می‌شناسد.',
    },
    {
      sentence: 'Wir kennen das Lied.',
      english: 'We know the song.',
      russian: 'Мы знаем эту песню.',
      farsi: 'ما این آهنگ را می‌شناسیم.',
    },
    {
      sentence: 'Sie kennt die Stadt.',
      english: 'She knows the city.',
      russian: 'Она знает город.',
      farsi: 'او شهر را می‌شناسد.',
    },
    {
      sentence: 'Kennst du ihn?',
      english: 'Do you know him?',
      russian: 'Ты знаешь его?',
      farsi: 'آیا او را می‌شناسی؟',
    },
    {
      sentence: 'Ich kenne diese Frau.',
      english: 'I know this woman.',
      russian: 'Я знаю эту женщину.',
      farsi: 'من این زن را می‌شناسم.',
    },
    {
      sentence: 'Wir kennen den Weg.',
      english: 'We know the way.',
      russian: 'Мы знаем дорогу.',
      farsi: 'ما راه را می‌شناسیم.',
    },
    {
      sentence: 'Kennt er das Buch?',
      english: 'Does he know the book?',
      russian: 'Он знает эту книгу?',
      farsi: 'آیا او این کتاب را می‌شناسد؟',
    },
    {
      sentence: 'Ich kenne die Antwort.',
      english: 'I know the answer.',
      russian: 'Я знаю ответ.',
      farsi: 'من جواب را می‌دانم.',
    },
    {
      sentence: 'Sie kennen das Problem.',
      english: 'They know the problem.',
      russian: 'Они знают проблему.',
      farsi: 'آنها مشکل را می‌دانند.',
    },
    {
      sentence: 'Ich habe ihn gekannt.',
      english: 'I knew him.',
      russian: 'Я знал его.',
      farsi: 'من او را می‌شناختم.',
    },
    {
      sentence: 'Er hat sie gekannt.',
      english: 'He knew her.',
      russian: 'Он знал её.',
      farsi: 'او او را می‌شناخت.',
    },
    {
      sentence: 'Wir haben das Lied gekannt.',
      english: 'We knew the song.',
      russian: 'Мы знали эту песню.',
      farsi: 'ما این آهنگ را می‌شناختیم.',
    },
    {
      sentence: 'Sie hat die Stadt gekannt.',
      english: 'She knew the city.',
      russian: 'Она знала город.',
      farsi: 'او شهر را می‌شناخت.',
    },
    {
      sentence: 'Hast du ihn gekannt?',
      english: 'Did you know him?',
      russian: 'Ты знал его?',
      farsi: 'آیا او را می‌شناختی؟',
    },
    {
      sentence: 'Ich habe diese Frau gekannt.',
      english: 'I knew this woman.',
      russian: 'Я знал эту женщину.',
      farsi: 'من این زن را می‌شناختم.',
    },
    {
      sentence: 'Wir haben den Weg gekannt.',
      english: 'We knew the way.',
      russian: 'Мы знали дорогу.',
      farsi: 'ما راه را می‌شناختیم.',
    },
    {
      sentence: 'Hat er das Buch gekannt?',
      english: 'Did he know the book?',
      russian: 'Он знал эту книгу?',
      farsi: 'آیا او این کتاب را می‌شناخت؟',
    },
    {
      sentence: 'Ich habe die Antwort gekannt.',
      english: 'I knew the answer.',
      russian: 'Я знал ответ.',
      farsi: 'من جواب را می‌دانستم.',
    },
    {
      sentence: 'Sie haben das Problem gekannt.',
      english: 'They knew the problem.',
      russian: 'Они знали проблему.',
      farsi: 'آنها مشکل را می‌دانستند.',
    },
    {
      sentence: 'Ich werde ihn kennen.',
      english: 'I will know him.',
      russian: 'Я буду знать его.',
      farsi: 'من او را خواهم شناخت.',
    },
    {
      sentence: 'Er wird sie kennen.',
      english: 'He will know her.',
      russian: 'Он будет знать её.',
      farsi: 'او او را خواهد شناخت.',
    },
    {
      sentence: 'Wir werden das Lied kennen.',
      english: 'We will know the song.',
      russian: 'Мы будем знать эту песню.',
      farsi: 'ما این آهنگ را خواهیم شناخت.',
    },
    {
      sentence: 'Sie wird die Stadt kennen.',
      english: 'She will know the city.',
      russian: 'Она будет знать город.',
      farsi: 'او شهر را خواهد شناخت.',
    },
    {
      sentence: 'Wirst du ihn kennen?',
      english: 'Will you know him?',
      russian: 'Ты будешь знать его?',
      farsi: 'آیا او را خواهی شناخت؟',
    },
    {
      sentence: 'Ich werde diese Frau kennen.',
      english: 'I will know this woman.',
      russian: 'Я буду знать эту женщину.',
      farsi: 'من این زن را خواهم شناخت.',
    },
    {
      sentence: 'Wir werden den Weg kennen.',
      english: 'We will know the way.',
      russian: 'Мы будем знать дорогу.',
      farsi: 'ما راه را خواهیم شناخت.',
    },
    {
      sentence: 'Wird er das Buch kennen?',
      english: 'Will he know the book?',
      russian: 'Он будет знать эту книгу?',
      farsi: 'آیا او این کتاب را خواهد شناخت؟',
    },
    {
      sentence: 'Ich werde die Antwort kennen.',
      english: 'I will know the answer.',
      russian: 'Я буду знать ответ.',
      farsi: 'من جواب را خواهم دانست.',
    },
    {
      sentence: 'Sie werden das Problem kennen.',
      english: 'They will know the problem.',
      russian: 'Они будут знать проблему.',
      farsi: 'آنها مشکل را خواهند دانست.',
    },
    {
      sentence: 'Das Buch liegt auf dem Tisch.',
      english: 'The book is lying on the table.',
      russian: 'Книга лежит на столе.',
      farsi: 'کتاب روی میز قرار دارد.',
    },
    {
      sentence: 'Der Hund liegt auf dem Boden.',
      english: 'The dog is lying on the floor.',
      russian: 'Собака лежит на полу.',
      farsi: 'سگ روی زمین قرار دارد.',
    },
    {
      sentence: 'Die Katze liegt auf dem Sofa.',
      english: 'The cat is lying on the sofa.',
      russian: 'Кошка лежит на диване.',
      farsi: 'گربه روی مبل قرار دارد.',
    },
    {
      sentence: 'Er liegt im Bett.',
      english: 'He is lying in bed.',
      russian: 'Он лежит в кровати.',
      farsi: 'او در تخت خوابیده است.',
    },
    {
      sentence: 'Das Handy liegt auf dem Stuhl.',
      english: 'The phone is lying on the chair.',
      russian: 'Телефон лежит на стуле.',
      farsi: 'تلفن روی صندلی قرار دارد.',
    },
    {
      sentence: 'Der Ball liegt im Garten.',
      english: 'The ball is lying in the garden.',
      russian: 'Мяч лежит в саду.',
      farsi: 'توپ در باغ قرار دارد.',
    },
    {
      sentence: 'Der Schlüssel liegt auf dem Regal.',
      english: 'The key is lying on the shelf.',
      russian: 'Ключ лежит на полке.',
      farsi: 'کلید روی قفسه قرار دارد.',
    },
    {
      sentence: 'Die Zeitung liegt auf dem Tisch.',
      english: 'The newspaper is lying on the table.',
      russian: 'Газета лежит на столе.',
      farsi: 'روزنامه روی میز قرار دارد.',
    },
    {
      sentence: 'Die Brille liegt neben dem Buch.',
      english: 'The glasses are lying next to the book.',
      russian: 'Очки лежат рядом с книгой.',
      farsi: 'عینک در کنار کتاب قرار دارد.',
    },
    {
      sentence: 'Das Bild liegt auf dem Boden.',
      english: 'The picture is lying on the floor.',
      russian: 'Картина лежит на полу.',
      farsi: 'عکس روی زمین قرار دارد.',
    },
    {
      sentence: 'Das Buch hat auf dem Tisch gelegen.',
      english: 'The book was lying on the table.',
      russian: 'Книга лежала на столе.',
      farsi: 'کتاب روی میز قرار داشت.',
    },
    {
      sentence: 'Der Hund hat auf dem Boden gelegen.',
      english: 'The dog was lying on the floor.',
      russian: 'Собака лежала на полу.',
      farsi: 'سگ روی زمین قرار داشت.',
    },
    {
      sentence: 'Die Katze hat auf dem Sofa gelegen.',
      english: 'The cat was lying on the sofa.',
      russian: 'Кошка лежала на диване.',
      farsi: 'گربه روی مبل قرار داشت.',
    },
    {
      sentence: 'Er hat im Bett gelegen.',
      english: 'He was lying in bed.',
      russian: 'Он лежал в кровати.',
      farsi: 'او در تخت خوابیده بود.',
    },
    {
      sentence: 'Das Handy hat auf dem Stuhl gelegen.',
      english: 'The phone was lying on the chair.',
      russian: 'Телефон лежал на стуле.',
      farsi: 'تلفن روی صندلی قرار داشت.',
    },
    {
      sentence: 'Der Ball hat im Garten gelegen.',
      english: 'The ball was lying in the garden.',
      russian: 'Мяч лежал в саду.',
      farsi: 'توپ در باغ قرار داشت.',
    },
    {
      sentence: 'Der Schlüssel hat auf dem Regal gelegen.',
      english: 'The key was lying on the shelf.',
      russian: 'Ключ лежал на полке.',
      farsi: 'کلید روی قفسه قرار داشت.',
    },
    {
      sentence: 'Die Zeitung hat auf dem Tisch gelegen.',
      english: 'The newspaper was lying on the table.',
      russian: 'Газета лежала на столе.',
      farsi: 'روزنامه روی میز قرار داشت.',
    },
    {
      sentence: 'Die Brille hat neben dem Buch gelegen.',
      english: 'The glasses were lying next to the book.',
      russian: 'Очки лежали рядом с книгой.',
      farsi: 'عینک در کنار کتاب قرار داشت.',
    },
    {
      sentence: 'Das Bild hat auf dem Boden gelegen.',
      english: 'The picture was lying on the floor.',
      russian: 'Картина лежала на полу.',
      farsi: 'عکس روی زمین قرار داشت.',
    },
    {
      sentence: 'Das Buch wird auf dem Tisch liegen.',
      english: 'The book will be lying on the table.',
      russian: 'Книга будет лежать на столе.',
      farsi: 'کتاب روی میز قرار خواهد داشت.',
    },
    {
      sentence: 'Der Hund wird auf dem Boden liegen.',
      english: 'The dog will be lying on the floor.',
      russian: 'Собака будет лежать на полу.',
      farsi: 'سگ روی زمین قرار خواهد داشت.',
    },
    {
      sentence: 'Die Katze wird auf dem Sofa liegen.',
      english: 'The cat will be lying on the sofa.',
      russian: 'Кошка будет лежать на диване.',
      farsi: 'گربه روی مبل قرار خواهد داشت.',
    },
    {
      sentence: 'Er wird im Bett liegen.',
      english: 'He will be lying in bed.',
      russian: 'Он будет лежать в кровати.',
      farsi: 'او در تخت خواهد خوابید.',
    },
    {
      sentence: 'Das Handy wird auf dem Stuhl liegen.',
      english: 'The phone will be lying on the chair.',
      russian: 'Телефон будет лежать на стуле.',
      farsi: 'تلفن روی صندلی قرار خواهد داشت.',
    },
    {
      sentence: 'Der Ball wird im Garten liegen.',
      english: 'The ball will be lying in the garden.',
      russian: 'Мяч будет лежать в саду.',
      farsi: 'توپ در باغ قرار خواهد داشت.',
    },
    {
      sentence: 'Der Schlüssel wird auf dem Regal liegen.',
      english: 'The key will be lying on the shelf.',
      russian: 'Ключ будет лежать на полке.',
      farsi: 'کلید روی قفسه قرار خواهد داشت.',
    },
    {
      sentence: 'Die Zeitung wird auf dem Tisch liegen.',
      english: 'The newspaper will be lying on the table.',
      russian: 'Газета будет лежать на столе.',
      farsi: 'روزنامه روی میز قرار خواهد داشت.',
    },
    {
      sentence: 'Die Brille wird neben dem Buch liegen.',
      english: 'The glasses will be lying next to the book.',
      russian: 'Очки будут лежать рядом с книгой.',
      farsi: 'عینک در کنار کتاب قرار خواهد داشت.',
    },
    {
      sentence: 'Das Bild wird auf dem Boden liegen.',
      english: 'The picture will be lying on the floor.',
      russian: 'Картина будет лежать на полу.',
      farsi: 'عکس روی زمین قرار خواهد داشت.',
    },
    {
      sentence: 'Ich arbeite im Büro.',
      english: 'I work in the office.',
      russian: 'Я работаю в офисе.',
      farsi: 'من در دفتر کار می‌کنم.',
    },
    {
      sentence: 'Er arbeitet als Lehrer.',
      english: 'He works as a teacher.',
      russian: 'Он работает учителем.',
      farsi: 'او به عنوان معلم کار می‌کند.',
    },
    {
      sentence: 'Sie arbeitet in einer Bank.',
      english: 'She works in a bank.',
      russian: 'Она работает в банке.',
      farsi: 'او در بانک کار می‌کند.',
    },
    {
      sentence: 'Wir arbeiten zusammen.',
      english: 'We work together.',
      russian: 'Мы работаем вместе.',
      farsi: 'ما با هم کار می‌کنیم.',
    },
    {
      sentence: 'Sie arbeiten zu Hause.',
      english: 'They work at home.',
      russian: 'Они работают дома.',
      farsi: 'آنها در خانه کار می‌کنند.',
    },
    {
      sentence: 'Arbeitest du hier?',
      english: 'Do you work here?',
      russian: 'Ты работаешь здесь?',
      farsi: 'آیا اینجا کار می‌کنی؟',
    },
    {
      sentence: 'Ich arbeite jeden Tag.',
      english: 'I work every day.',
      russian: 'Я работаю каждый день.',
      farsi: 'من هر روز کار می‌کنم.',
    },
    {
      sentence: 'Er arbeitet viel.',
      english: 'He works a lot.',
      russian: 'Он много работает.',
      farsi: 'او زیاد کار می‌کند.',
    },
    {
      sentence: 'Sie arbeitet hart.',
      english: 'She works hard.',
      russian: 'Она усердно работает.',
      farsi: 'او سخت کار می‌کند.',
    },
    {
      sentence: 'Wir arbeiten an einem Projekt.',
      english: 'We are working on a project.',
      russian: 'Мы работаем над проектом.',
      farsi: 'ما روی یک پروژه کار می‌کنیم.',
    },
    {
      sentence: 'Ich habe gestern gearbeitet.',
      english: 'I worked yesterday.',
      russian: 'Я работал вчера.',
      farsi: 'من دیروز کار کردم.',
    },
    {
      sentence: 'Er hat als Lehrer gearbeitet.',
      english: 'He worked as a teacher.',
      russian: 'Он работал учителем.',
      farsi: 'او به عنوان معلم کار می‌کرد.',
    },
    {
      sentence: 'Sie hat in einer Bank gearbeitet.',
      english: 'She worked in a bank.',
      russian: 'Она работала в банке.',
      farsi: 'او در بانک کار می‌کرد.',
    },
    {
      sentence: 'Wir haben zusammen gearbeitet.',
      english: 'We worked together.',
      russian: 'Мы работали вместе.',
      farsi: 'ما با هم کار کردیم.',
    },
    {
      sentence: 'Sie haben zu Hause gearbeitet.',
      english: 'They worked at home.',
      russian: 'Они работали дома.',
      farsi: 'آنها در خانه کار می‌کردند.',
    },
    {
      sentence: 'Hast du hier gearbeitet?',
      english: 'Did you work here?',
      russian: 'Ты работал здесь?',
      farsi: 'آیا اینجا کار کردی؟',
    },
    {
      sentence: 'Ich habe jeden Tag gearbeitet.',
      english: 'I worked every day.',
      russian: 'Я работал каждый день.',
      farsi: 'من هر روز کار می‌کردم.',
    },
    {
      sentence: 'Er hat viel gearbeitet.',
      english: 'He worked a lot.',
      russian: 'Он много работал.',
      farsi: 'او زیاد کار می‌کرد.',
    },
    {
      sentence: 'Sie hat hart gearbeitet.',
      english: 'She worked hard.',
      russian: 'Она усердно работала.',
      farsi: 'او سخت کار می‌کرد.',
    },
    {
      sentence: 'Wir haben an einem Projekt gearbeitet.',
      english: 'We worked on a project.',
      russian: 'Мы работали над проектом.',
      farsi: 'ما روی یک پروژه کار می‌کردیم.',
    },
    {
      sentence: 'Ich werde morgen arbeiten.',
      english: 'I will work tomorrow.',
      russian: 'Я буду работать завтра.',
      farsi: 'من فردا کار خواهم کرد.',
    },
    {
      sentence: 'Er wird als Lehrer arbeiten.',
      english: 'He will work as a teacher.',
      russian: 'Он будет работать учителем.',
      farsi: 'او به عنوان معلم کار خواهد کرد.',
    },
    {
      sentence: 'Sie wird in einer Bank arbeiten.',
      english: 'She will work in a bank.',
      russian: 'Она будет работать в банке.',
      farsi: 'او در بانک کار خواهد کرد.',
    },
    {
      sentence: 'Wir werden zusammen arbeiten.',
      english: 'We will work together.',
      russian: 'Мы будем работать вместе.',
      farsi: 'ما با هم کار خواهیم کرد.',
    },
    {
      sentence: 'Sie werden zu Hause arbeiten.',
      english: 'They will work at home.',
      russian: 'Они будут работать дома.',
      farsi: 'آنها در خانه کار خواهند کرد.',
    },
    {
      sentence: 'Wirst du hier arbeiten?',
      english: 'Will you work here?',
      russian: 'Ты будешь работать здесь?',
      farsi: 'آیا اینجا کار خواهی کرد؟',
    },
    {
      sentence: 'Ich werde jeden Tag arbeiten.',
      english: 'I will work every day.',
      russian: 'Я буду работать каждый день.',
      farsi: 'من هر روز کار خواهم کرد.',
    },
    {
      sentence: 'Er wird viel arbeiten.',
      english: 'He will work a lot.',
      russian: 'Он будет много работать.',
      farsi: 'او زیاد کار خواهد کرد.',
    },
    {
      sentence: 'Sie wird hart arbeiten.',
      english: 'She will work hard.',
      russian: 'Она будет усердно работать.',
      farsi: 'او سخت کار خواهد کرد.',
    },
    {
      sentence: 'Wir werden an einem Projekt arbeiten.',
      english: 'We will work on a project.',
      russian: 'Мы будем работать над проектом.',
      farsi: 'ما روی یک پروژه کار خواهیم کرد.',
    },
    {
      sentence: 'Ich lebe in Deutschland.',
      english: 'I live in Germany.',
      russian: 'Я живу в Германии.',
      farsi: 'من در آلمان زندگی می‌کنم.',
    },
    {
      sentence: 'Er lebt in Berlin.',
      english: 'He lives in Berlin.',
      russian: 'Он живет в Берлине.',
      farsi: 'او در برلین زندگی می‌کند.',
    },
    {
      sentence: 'Sie lebt in einer Wohnung.',
      english: 'She lives in an apartment.',
      russian: 'Она живет в квартире.',
      farsi: 'او در یک آپارتمان زندگی می‌کند.',
    },
    {
      sentence: 'Wir leben zusammen.',
      english: 'We live together.',
      russian: 'Мы живем вместе.',
      farsi: 'ما با هم زندگی می‌کنیم.',
    },
    {
      sentence: 'Sie leben auf dem Land.',
      english: 'They live in the countryside.',
      russian: 'Они живут в деревне.',
      farsi: 'آنها در روستا زندگی می‌کنند.',
    },
    {
      sentence: 'Lebst du hier?',
      english: 'Do you live here?',
      russian: 'Ты живешь здесь?',
      farsi: 'آیا اینجا زندگی می‌کنی؟',
    },
    {
      sentence: 'Ich lebe seit fünf Jahren hier.',
      english: 'I have been living here for five years.',
      russian: 'Я живу здесь пять лет.',
      farsi: 'من پنج سال است که اینجا زندگی می‌کنم.',
    },
    {
      sentence: 'Er lebt mit seiner Familie.',
      english: 'He lives with his family.',
      russian: 'Он живет со своей семьей.',
      farsi: 'او با خانواده‌اش زندگی می‌کند.',
    },
    {
      sentence: 'Sie lebt allein.',
      english: 'She lives alone.',
      russian: 'Она живет одна.',
      farsi: 'او تنها زندگی می‌کند.',
    },
    {
      sentence: 'Wir leben in einem Haus.',
      english: 'We live in a house.',
      russian: 'Мы живем в доме.',
      farsi: 'ما در یک خانه زندگی می‌کنیم.',
    },
    {
      sentence: 'Ich habe in Frankreich gelebt.',
      english: 'I lived in France.',
      russian: 'Я жил во Франции.',
      farsi: 'من در فرانسه زندگی می‌کردم.',
    },
    {
      sentence: 'Er hat in Berlin gelebt.',
      english: 'He lived in Berlin.',
      russian: 'Он жил в Берлине.',
      farsi: 'او در برلین زندگی می‌کرد.',
    },
    {
      sentence: 'Sie hat in einer Wohnung gelebt.',
      english: 'She lived in an apartment.',
      russian: 'Она жила в квартире.',
      farsi: 'او در یک آپارتمان زندگی می‌کرد.',
    },
    {
      sentence: 'Wir haben zusammen gelebt.',
      english: 'We lived together.',
      russian: 'Мы жили вместе.',
      farsi: 'ما با هم زندگی می‌کردیم.',
    },
    {
      sentence: 'Sie haben auf dem Land gelebt.',
      english: 'They lived in the countryside.',
      russian: 'Они жили в деревне.',
      farsi: 'آنها در روستا زندگی می‌کردند.',
    },
    {
      sentence: 'Hast du hier gelebt?',
      english: 'Did you live here?',
      russian: 'Ты жил здесь?',
      farsi: 'آیا اینجا زندگی می‌کردی؟',
    },
    {
      sentence: 'Ich habe fünf Jahre hier gelebt.',
      english: 'I lived here for five years.',
      russian: 'Я жил здесь пять лет.',
      farsi: 'من پنج سال اینجا زندگی می‌کردم.',
    },
    {
      sentence: 'Er hat mit seiner Familie gelebt.',
      english: 'He lived with his family.',
      russian: 'Он жил со своей семьей.',
      farsi: 'او با خانواده‌اش زندگی می‌کرد.',
    },
    {
      sentence: 'Sie hat allein gelebt.',
      english: 'She lived alone.',
      russian: 'Она жила одна.',
      farsi: 'او تنها زندگی می‌کرد.',
    },
    {
      sentence: 'Wir haben in einem Haus gelebt.',
      english: 'We lived in a house.',
      russian: 'Мы жили в доме.',
      farsi: 'ما در یک خانه زندگی می‌کردیم.',
    },
    {
      sentence: 'Ich werde in Deutschland leben.',
      english: 'I will live in Germany.',
      russian: 'Я буду жить в Германии.',
      farsi: 'من در آلمان زندگی خواهم کرد.',
    },
    {
      sentence: 'Er wird in Berlin leben.',
      english: 'He will live in Berlin.',
      russian: 'Он будет жить в Берлине.',
      farsi: 'او در برلین زندگی خواهد کرد.',
    },
    {
      sentence: 'Sie wird in einer Wohnung leben.',
      english: 'She will live in an apartment.',
      russian: 'Она будет жить в квартире.',
      farsi: 'او در یک آپارتمان زندگی خواهد کرد.',
    },
    {
      sentence: 'Wir werden zusammen leben.',
      english: 'We will live together.',
      russian: 'Мы будем жить вместе.',
      farsi: 'ما با هم زندگی خواهیم کرد.',
    },
    {
      sentence: 'Sie werden auf dem Land leben.',
      english: 'They will live in the countryside.',
      russian: 'Они будут жить в деревне.',
      farsi: 'آنها در روستا زندگی خواهند کرد.',
    },
    {
      sentence: 'Wirst du hier leben?',
      english: 'Will you live here?',
      russian: 'Ты будешь жить здесь?',
      farsi: 'آیا اینجا زندگی خواهی کرد؟',
    },
    {
      sentence: 'Ich werde fünf Jahre hier leben.',
      english: 'I will live here for five years.',
      russian: 'Я буду жить здесь пять лет.',
      farsi: 'من پنج سال اینجا زندگی خواهم کرد.',
    },
    {
      sentence: 'Er wird mit seiner Familie leben.',
      english: 'He will live with his family.',
      russian: 'Он будет жить со своей семьей.',
      farsi: 'او با خانواده‌اش زندگی خواهد کرد.',
    },
    {
      sentence: 'Sie wird allein leben.',
      english: 'She will live alone.',
      russian: 'Она будет жить одна.',
      farsi: 'او تنها زندگی خواهد کرد.',
    },
    {
      sentence: 'Wir werden in einem Haus leben.',
      english: 'We will live in a house.',
      russian: 'Мы будем жить в доме.',
      farsi: 'ما در یک خانه زندگی خواهیم کرد.',
    },
    {
      sentence: 'Ich liebe dich.',
      english: 'I love you.',
      russian: 'Я люблю тебя.',
      farsi: 'من تو را دوست دارم.',
    },
    {
      sentence: 'Er liebt seine Familie.',
      english: 'He loves his family.',
      russian: 'Он любит свою семью.',
      farsi: 'او خانواده‌اش را دوست دارد.',
    },
    {
      sentence: 'Sie liebt ihren Hund.',
      english: 'She loves her dog.',
      russian: 'Она любит свою собаку.',
      farsi: 'او سگش را دوست دارد.',
    },
    {
      sentence: 'Wir lieben unsere Freunde.',
      english: 'We love our friends.',
      russian: 'Мы любим наших друзей.',
      farsi: 'ما دوستانمان را دوست داریم.',
    },
    {
      sentence: 'Sie lieben die Natur.',
      english: 'They love nature.',
      russian: 'Они любят природу.',
      farsi: 'آنها طبیعت را دوست دارند.',
    },
    {
      sentence: 'Liebst du Musik?',
      english: 'Do you love music?',
      russian: 'Ты любишь музыку?',
      farsi: 'آیا موسیقی را دوست داری؟',
    },
    {
      sentence: 'Ich liebe es, zu reisen.',
      english: 'I love traveling.',
      russian: 'Я люблю путешествовать.',
      farsi: 'من عاشق سفر کردن هستم.',
    },
    {
      sentence: 'Er liebt Fußball.',
      english: 'He loves football.',
      russian: 'Он любит футбол.',
      farsi: 'او فوتبال را دوست دارد.',
    },
    {
      sentence: 'Sie liebt das Meer.',
      english: 'She loves the sea.',
      russian: 'Она любит море.',
      farsi: 'او دریا را دوست دارد.',
    },
    {
      sentence: 'Wir lieben es, zu kochen.',
      english: 'We love cooking.',
      russian: 'Мы любим готовить.',
      farsi: 'ما آشپزی را دوست داریم.',
    },
    {
      sentence: 'Ich habe dich immer geliebt.',
      english: 'I have always loved you.',
      russian: 'Я всегда любил тебя.',
      farsi: 'من همیشه تو را دوست داشته‌ام.',
    },
    {
      sentence: 'Er hat seine Arbeit geliebt.',
      english: 'He loved his job.',
      russian: 'Он любил свою работу.',
      farsi: 'او کارش را دوست داشت.',
    },
    {
      sentence: 'Sie hat ihre Kinder geliebt.',
      english: 'She loved her children.',
      russian: 'Она любила своих детей.',
      farsi: 'او بچه‌هایش را دوست داشت.',
    },
    {
      sentence: 'Wir haben das Leben geliebt.',
      english: 'We loved life.',
      russian: 'Мы любили жизнь.',
      farsi: 'ما زندگی را دوست داشتیم.',
    },
    {
      sentence: 'Sie haben die Musik geliebt.',
      english: 'They loved the music.',
      russian: 'Они любили музыку.',
      farsi: 'آنها موسیقی را دوست داشتند.',
    },
    {
      sentence: 'Hast du mich geliebt?',
      english: 'Did you love me?',
      russian: 'Ты любил меня?',
      farsi: 'آیا من را دوست داشتی؟',
    },
    {
      sentence: 'Ich habe es geliebt, zu lesen.',
      english: 'I loved reading.',
      russian: 'Я любил читать.',
      farsi: 'من عاشق خواندن بودم.',
    },
    {
      sentence: 'Er hat das Reisen geliebt.',
      english: 'He loved traveling.',
      russian: 'Он любил путешествовать.',
      farsi: 'او سفر کردن را دوست داشت.',
    },
    {
      sentence: 'Sie hat die Natur geliebt.',
      english: 'She loved nature.',
      russian: 'Она любила природу.',
      farsi: 'او طبیعت را دوست داشت.',
    },
    {
      sentence: 'Wir haben das Meer geliebt.',
      english: 'We loved the sea.',
      russian: 'Мы любили море.',
      farsi: 'ما دریا را دوست داشتیم.',
    },
    {
      sentence: 'Ich werde dich immer lieben.',
      english: 'I will always love you.',
      russian: 'Я всегда буду любить тебя.',
      farsi: 'من همیشه تو را دوست خواهم داشت.',
    },
    {
      sentence: 'Er wird seine Familie lieben.',
      english: 'He will love his family.',
      russian: 'Он будет любить свою семью.',
      farsi: 'او خانواده‌اش را دوست خواهد داشت.',
    },
    {
      sentence: 'Sie wird ihren Hund lieben.',
      english: 'She will love her dog.',
      russian: 'Она будет любить свою собаку.',
      farsi: 'او سگش را دوست خواهد داشت.',
    },
    {
      sentence: 'Wir werden unsere Freunde lieben.',
      english: 'We will love our friends.',
      russian: 'Мы будем любить наших друзей.',
      farsi: 'ما دوستانمان را دوست خواهیم داشت.',
    },
    {
      sentence: 'Sie werden die Natur lieben.',
      english: 'They will love nature.',
      russian: 'Они будут любить природу.',
      farsi: 'آنها طبیعت را دوست خواهند داشت.',
    },
    {
      sentence: 'Wirst du mich lieben?',
      english: 'Will you love me?',
      russian: 'Ты будешь любить меня?',
      farsi: 'آیا من را دوست خواهی داشت؟',
    },
    {
      sentence: 'Ich werde es lieben, zu reisen.',
      english: 'I will love traveling.',
      russian: 'Я буду любить путешествовать.',
      farsi: 'من عاشق سفر کردن خواهم بود.',
    },
    {
      sentence: 'Er wird Fußball lieben.',
      english: 'He will love football.',
      russian: 'Он будет любить футбол.',
      farsi: 'او فوتبال را دوست خواهد داشت.',
    },
    {
      sentence: 'Sie wird das Meer lieben.',
      english: 'She will love the sea.',
      russian: 'Она будет любить море.',
      farsi: 'او دریا را دوست خواهد داشت.',
    },
    {
      sentence: 'Wir werden es lieben, zu kochen.',
      english: 'We will love cooking.',
      russian: 'Мы будем любить готовить.',
      farsi: 'ما آشپزی را دوست خواهیم داشت.',
    },
    {
      sentence: 'Ich spreche Deutsch.',
      english: 'I speak German.',
      russian: 'Я говорю по-немецки.',
      farsi: 'من آلمانی صحبت می‌کنم.',
    },
    {
      sentence: 'Er spricht Englisch.',
      english: 'He speaks English.',
      russian: 'Он говорит по-английски.',
      farsi: 'او انگلیسی صحبت می‌کند.',
    },
    {
      sentence: 'Sie spricht Französisch.',
      english: 'She speaks French.',
      russian: 'Она говорит по-французски.',
      farsi: 'او فرانسوی صحبت می‌کند.',
    },
    {
      sentence: 'Wir sprechen Spanisch.',
      english: 'We speak Spanish.',
      russian: 'Мы говорим по-испански.',
      farsi: 'ما اسپانیایی صحبت می‌کنیم.',
    },
    {
      sentence: 'Sie sprechen Italienisch.',
      english: 'They speak Italian.',
      russian: 'Они говорят по-итальянски.',
      farsi: 'آنها ایتالیایی صحبت می‌کنند.',
    },
    {
      sentence: 'Sprichst du Russisch?',
      english: 'Do you speak Russian?',
      russian: 'Ты говоришь по-русски?',
      farsi: 'آیا روسی صحبت می‌کنی؟',
    },
    {
      sentence: 'Ich spreche ein wenig Deutsch.',
      english: 'I speak a little German.',
      russian: 'Я немного говорю по-немецки.',
      farsi: 'من کمی آلمانی صحبت می‌کنم.',
    },
    {
      sentence: 'Er spricht sehr gut Englisch.',
      english: 'He speaks English very well.',
      russian: 'Он очень хорошо говорит по-английски.',
      farsi: 'او بسیار خوب انگلیسی صحبت می‌کند.',
    },
    {
      sentence: 'Sie spricht fließend Französisch.',
      english: 'She speaks French fluently.',
      russian: 'Она свободно говорит по-французски.',
      farsi: 'او به صورت روان فرانسوی صحبت می‌کند.',
    },
    {
      sentence: 'Wir sprechen nur ein bisschen Spanisch.',
      english: 'We speak only a little Spanish.',
      russian: 'Мы говорим только немного по-испански.',
      farsi: 'ما فقط کمی اسپانیایی صحبت می‌کنیم.',
    },
    {
      sentence: 'Ich habe gestern mit ihm gesprochen.',
      english: 'I spoke with him yesterday.',
      russian: 'Я говорил с ним вчера.',
      farsi: 'من دیروز با او صحبت کردم.',
    },
    {
      sentence: 'Er hat über das Problem gesprochen.',
      english: 'He talked about the problem.',
      russian: 'Он говорил о проблеме.',
      farsi: 'او درباره مشکل صحبت کرد.',
    },
    {
      sentence: 'Sie hat mit ihrem Chef gesprochen.',
      english: 'She spoke with her boss.',
      russian: 'Она говорила со своим начальником.',
      farsi: 'او با رئیسش صحبت کرد.',
    },
    {
      sentence: 'Wir haben viel gesprochen.',
      english: 'We talked a lot.',
      russian: 'Мы много говорили.',
      farsi: 'ما زیاد صحبت کردیم.',
    },
    {
      sentence: 'Sie haben über ihre Pläne gesprochen.',
      english: 'They talked about their plans.',
      russian: 'Они говорили о своих планах.',
      farsi: 'آنها درباره برنامه‌هایشان صحبت کردند.',
    },
    {
      sentence: 'Hast du mit ihm gesprochen?',
      english: 'Did you speak with him?',
      russian: 'Ты говорил с ним?',
      farsi: 'آیا با او صحبت کردی؟',
    },
    {
      sentence: 'Ich habe lange nicht gesprochen.',
      english: "I haven't spoken for a long time.",
      russian: 'Я давно не говорил.',
      farsi: 'من مدت زیادی صحبت نکرده‌ام.',
    },
    {
      sentence: 'Er hat schnell gesprochen.',
      english: 'He spoke quickly.',
      russian: 'Он говорил быстро.',
      farsi: 'او سریع صحبت کرد.',
    },
    {
      sentence: 'Sie hat leise gesprochen.',
      english: 'She spoke quietly.',
      russian: 'Она говорила тихо.',
      farsi: 'او آرام صحبت کرد.',
    },
    {
      sentence: 'Wir haben laut gesprochen.',
      english: 'We spoke loudly.',
      russian: 'Мы говорили громко.',
      farsi: 'ما با صدای بلند صحبت کردیم.',
    },
    {
      sentence: 'Ich werde morgen mit ihm sprechen.',
      english: 'I will speak with him tomorrow.',
      russian: 'Я буду говорить с ним завтра.',
      farsi: 'من فردا با او صحبت خواهم کرد.',
    },
    {
      sentence: 'Er wird über das Problem sprechen.',
      english: 'He will talk about the problem.',
      russian: 'Он будет говорить о проблеме.',
      farsi: 'او درباره مشکل صحبت خواهد کرد.',
    },
    {
      sentence: 'Sie wird mit ihrem Chef sprechen.',
      english: 'She will speak with her boss.',
      russian: 'Она будет говорить со своим начальником.',
      farsi: 'او با رئیسش صحبت خواهد کرد.',
    },
    {
      sentence: 'Wir werden viel sprechen.',
      english: 'We will talk a lot.',
      russian: 'Мы будем много говорить.',
      farsi: 'ما زیاد صحبت خواهیم کرد.',
    },
    {
      sentence: 'Sie werden über ihre Pläne sprechen.',
      english: 'They will talk about their plans.',
      russian: 'Они будут говорить о своих планах.',
      farsi: 'آنها درباره برنامه‌هایشان صحبت خواهند کرد.',
    },
    {
      sentence: 'Wirst du mit ihm sprechen?',
      english: 'Will you speak with him?',
      russian: 'Ты будешь говорить с ним?',
      farsi: 'آیا با او صحبت خواهی کرد؟',
    },
    {
      sentence: 'Ich werde lange sprechen.',
      english: 'I will speak for a long time.',
      russian: 'Я буду говорить долго.',
      farsi: 'من مدت زیادی صحبت خواهم کرد.',
    },
    {
      sentence: 'Er wird schnell sprechen.',
      english: 'He will speak quickly.',
      russian: 'Он будет говорить быстро.',
      farsi: 'او سریع صحبت خواهد کرد.',
    },
    {
      sentence: 'Sie wird leise sprechen.',
      english: 'She will speak quietly.',
      russian: 'Она будет говорить тихо.',
      farsi: 'او آرام صحبت خواهد کرد.',
    },
    {
      sentence: 'Wir werden laut sprechen.',
      english: 'We will speak loudly.',
      russian: 'Мы будем говорить громко.',
      farsi: 'ما با صدای بلند صحبت خواهیم کرد.',
    },
    {
      sentence: 'Ich suche meine Schlüssel.',
      english: 'I am looking for my keys.',
      russian: 'Я ищу свои ключи.',
      farsi: 'من دنبال کلیدهایم می‌گردم.',
    },
    {
      sentence: 'Er sucht seine Brille.',
      english: 'He is looking for his glasses.',
      russian: 'Он ищет свои очки.',
      farsi: 'او دنبال عینکش می‌گردد.',
    },
    {
      sentence: 'Sie sucht ihren Hund.',
      english: 'She is looking for her dog.',
      russian: 'Она ищет свою собаку.',
      farsi: 'او دنبال سگش می‌گردد.',
    },
    {
      sentence: 'Wir suchen ein neues Haus.',
      english: 'We are looking for a new house.',
      russian: 'Мы ищем новый дом.',
      farsi: 'ما دنبال خانه جدیدی می‌گردیم.',
    },
    {
      sentence: 'Sie suchen eine Wohnung.',
      english: 'They are looking for an apartment.',
      russian: 'Они ищут квартиру.',
      farsi: 'آنها دنبال یک آپارتمان می‌گردند.',
    },
    {
      sentence: 'Suchst du deinen Mantel?',
      english: 'Are you looking for your coat?',
      russian: 'Ты ищешь своё пальто?',
      farsi: 'آیا دنبال کتت می‌گردی؟',
    },
    {
      sentence: 'Ich suche einen neuen Job.',
      english: 'I am looking for a new job.',
      russian: 'Я ищу новую работу.',
      farsi: 'من دنبال یک شغل جدید می‌گردم.',
    },
    {
      sentence: 'Er sucht nach Antworten.',
      english: 'He is looking for answers.',
      russian: 'Он ищет ответы.',
      farsi: 'او دنبال پاسخ‌ها می‌گردد.',
    },
    {
      sentence: 'Sie sucht nach ihrem Freund.',
      english: 'She is looking for her friend.',
      russian: 'Она ищет своего друга.',
      farsi: 'او دنبال دوستش می‌گردد.',
    },
    {
      sentence: 'Wir suchen nach dem besten Angebot.',
      english: 'We are looking for the best offer.',
      russian: 'Мы ищем лучшее предложение.',
      farsi: 'ما دنبال بهترین پیشنهاد می‌گردیم.',
    },
    {
      sentence: 'Ich habe meine Schlüssel gesucht.',
      english: 'I looked for my keys.',
      russian: 'Я искал свои ключи.',
      farsi: 'من دنبال کلیدهایم گشتم.',
    },
    {
      sentence: 'Er hat seine Brille gesucht.',
      english: 'He looked for his glasses.',
      russian: 'Он искал свои очки.',
      farsi: 'او دنبال عینکش گشت.',
    },
    {
      sentence: 'Sie hat ihren Hund gesucht.',
      english: 'She looked for her dog.',
      russian: 'Она искала свою собаку.',
      farsi: 'او دنبال سگش گشت.',
    },
    {
      sentence: 'Wir haben ein neues Haus gesucht.',
      english: 'We looked for a new house.',
      russian: 'Мы искали новый дом.',
      farsi: 'ما دنبال خانه جدیدی گشتیم.',
    },
    {
      sentence: 'Sie haben eine Wohnung gesucht.',
      english: 'They looked for an apartment.',
      russian: 'Они искали квартиру.',
      farsi: 'آنها دنبال یک آپارتمان گشتند.',
    },
    {
      sentence: 'Hast du deinen Mantel gesucht?',
      english: 'Did you look for your coat?',
      russian: 'Ты искал своё пальто?',
      farsi: 'آیا دنبال کتت گشتی؟',
    },
    {
      sentence: 'Ich habe einen neuen Job gesucht.',
      english: 'I looked for a new job.',
      russian: 'Я искал новую работу.',
      farsi: 'من دنبال یک شغل جدید گشتم.',
    },
    {
      sentence: 'Er hat nach Antworten gesucht.',
      english: 'He looked for answers.',
      russian: 'Он искал ответы.',
      farsi: 'او دنبال پاسخ‌ها گشت.',
    },
    {
      sentence: 'Sie hat nach ihrem Freund gesucht.',
      english: 'She looked for her friend.',
      russian: 'Она искала своего друга.',
      farsi: 'او دنبال دوستش گشت.',
    },
    {
      sentence: 'Wir haben nach dem besten Angebot gesucht.',
      english: 'We looked for the best offer.',
      russian: 'Мы искали лучшее предложение.',
      farsi: 'ما دنبال بهترین پیشنهاد گشتیم.',
    },
    {
      sentence: 'Ich werde meine Schlüssel suchen.',
      english: 'I will look for my keys.',
      russian: 'Я буду искать свои ключи.',
      farsi: 'من دنبال کلیدهایم خواهم گشت.',
    },
    {
      sentence: 'Er wird seine Brille suchen.',
      english: 'He will look for his glasses.',
      russian: 'Он будет искать свои очки.',
      farsi: 'او دنبال عینکش خواهد گشت.',
    },
    {
      sentence: 'Sie wird ihren Hund suchen.',
      english: 'She will look for her dog.',
      russian: 'Она будет искать свою собаку.',
      farsi: 'او دنبال سگش خواهد گشت.',
    },
    {
      sentence: 'Wir werden ein neues Haus suchen.',
      english: 'We will look for a new house.',
      russian: 'Мы будем искать новый дом.',
      farsi: 'ما دنبال خانه جدیدی خواهیم گشت.',
    },
    {
      sentence: 'Sie werden eine Wohnung suchen.',
      english: 'They will look for an apartment.',
      russian: 'Они будут искать квартиру.',
      farsi: 'آنها دنبال یک آپارتمان خواهند گشت.',
    },
    {
      sentence: 'Wirst du deinen Mantel suchen?',
      english: 'Will you look for your coat?',
      russian: 'Ты будешь искать своё пальто?',
      farsi: 'آیا دنبال کتت خواهی گشت؟',
    },
    {
      sentence: 'Ich werde einen neuen Job suchen.',
      english: 'I will look for a new job.',
      russian: 'Я буду искать новую работу.',
      farsi: 'من دنبال یک شغل جدید خواهم گشت.',
    },
    {
      sentence: 'Er wird nach Antworten suchen.',
      english: 'He will look for answers.',
      russian: 'Он будет искать ответы.',
      farsi: 'او دنبال پاسخ‌ها خواهد گشت.',
    },
    {
      sentence: 'Sie wird nach ihrem Freund suchen.',
      english: 'She will look for her friend.',
      russian: 'Она будет искать своего друга.',
      farsi: 'او دنبال دوستش خواهد گشت.',
    },
    {
      sentence: 'Wir werden nach dem besten Angebot suchen.',
      english: 'We will look for the best offer.',
      russian: 'Мы будем искать лучшее предложение.',
      farsi: 'ما دنبال بهترین پیشنهاد خواهیم گشت.',
    },
    {
      sentence: 'Wie viel kostet das?',
      english: 'How much does this cost?',
      russian: 'Сколько это стоит?',
      farsi: 'این چقدر هزینه دارد؟',
    },
    {
      sentence: 'Das Buch kostet 10 Euro.',
      english: 'The book costs 10 euros.',
      russian: 'Эта книга стоит 10 евро.',
      farsi: 'این کتاب 10 یورو هزینه دارد.',
    },
    {
      sentence: 'Der Kaffee kostet 2 Euro.',
      english: 'The coffee costs 2 euros.',
      russian: 'Кофе стоит 2 евро.',
      farsi: 'این قهوه 2 یورو هزینه دارد.',
    },
    {
      sentence: 'Wie viel kostet ein Ticket?',
      english: 'How much does a ticket cost?',
      russian: 'Сколько стоит билет?',
      farsi: 'یک بلیط چقدر هزینه دارد؟',
    },
    {
      sentence: 'Das T-Shirt kostet 15 Euro.',
      english: 'The T-shirt costs 15 euros.',
      russian: 'Футболка стоит 15 евро.',
      farsi: 'این تی‌شرت 15 یورو هزینه دارد.',
    },
    {
      sentence: 'Der Film kostet 12 Euro.',
      english: 'The movie costs 12 euros.',
      russian: 'Фильм стоит 12 евро.',
      farsi: 'این فیلم 12 یورو هزینه دارد.',
    },
    {
      sentence: 'Wie viel kosten die Schuhe?',
      english: 'How much do the shoes cost?',
      russian: 'Сколько стоят эти туфли?',
      farsi: 'این کفش‌ها چقدر هزینه دارند؟',
    },
    {
      sentence: 'Die Tasche kostet 20 Euro.',
      english: 'The bag costs 20 euros.',
      russian: 'Сумка стоит 20 евро.',
      farsi: 'این کیف 20 یورو هزینه دارد.',
    },
    {
      sentence: 'Das Ticket kostet 5 Euro.',
      english: 'The ticket costs 5 euros.',
      russian: 'Билет стоит 5 евро.',
      farsi: 'این بلیط 5 یورو هزینه دارد.',
    },
    {
      sentence: 'Das Brot kostet 3 Euro.',
      english: 'The bread costs 3 euros.',
      russian: 'Хлеб стоит 3 евро.',
      farsi: 'این نان 3 یورو هزینه دارد.',
    },
    {
      sentence: 'Wie viel hat das Buch gekostet?',
      english: 'How much did the book cost?',
      russian: 'Сколько стоила эта книга?',
      farsi: 'این کتاب چقدر هزینه داشت؟',
    },
    {
      sentence: 'Der Kaffee hat 2 Euro gekostet.',
      english: 'The coffee cost 2 euros.',
      russian: 'Кофе стоил 2 евро.',
      farsi: 'این قهوه 2 یورو هزینه داشت.',
    },
    {
      sentence: 'Das T-Shirt hat 15 Euro gekostet.',
      english: 'The T-shirt cost 15 euros.',
      russian: 'Футболка стоила 15 евро.',
      farsi: 'این تی‌شرت 15 یورو هزینه داشت.',
    },
    {
      sentence: 'Der Film hat 12 Euro gekostet.',
      english: 'The movie cost 12 euros.',
      russian: 'Фильм стоил 12 евро.',
      farsi: 'این فیلم 12 یورو هزینه داشت.',
    },
    {
      sentence: 'Die Schuhe haben viel gekostet.',
      english: 'The shoes cost a lot.',
      russian: 'Туфли стоили дорого.',
      farsi: 'این کفش‌ها خیلی هزینه داشتند.',
    },
    {
      sentence: 'Die Tasche hat 20 Euro gekostet.',
      english: 'The bag cost 20 euros.',
      russian: 'Сумка стоила 20 евро.',
      farsi: 'این کیف 20 یورو هزینه داشت.',
    },
    {
      sentence: 'Das Ticket hat 5 Euro gekostet.',
      english: 'The ticket cost 5 euros.',
      russian: 'Билет стоил 5 евро.',
      farsi: 'این بلیط 5 یورو هزینه داشت.',
    },
    {
      sentence: 'Das Brot hat 3 Euro gekostet.',
      english: 'The bread cost 3 euros.',
      russian: 'Хлеб стоил 3 евро.',
      farsi: 'این نان 3 یورو هزینه داشت.',
    },
    {
      sentence: 'Die Bücher haben viel gekostet.',
      english: 'The books cost a lot.',
      russian: 'Книги стоили дорого.',
      farsi: 'این کتاب‌ها خیلی هزینه داشتند.',
    },
    {
      sentence: 'Die Reise hat viel Geld gekostet.',
      english: 'The trip cost a lot of money.',
      russian: 'Путешествие стоило много денег.',
      farsi: 'این سفر خیلی هزینه داشت.',
    },
    {
      sentence: 'Wie viel wird das Auto kosten?',
      english: 'How much will the car cost?',
      russian: 'Сколько будет стоить машина?',
      farsi: 'این ماشین چقدر هزینه خواهد داشت؟',
    },
    {
      sentence: 'Das Haus wird viel kosten.',
      english: 'The house will cost a lot.',
      russian: 'Дом будет стоить дорого.',
      farsi: 'این خانه خیلی هزینه خواهد داشت.',
    },
    {
      sentence: 'Der Urlaub wird teuer kosten.',
      english: 'The vacation will cost a lot.',
      russian: 'Отпуск будет стоить дорого.',
      farsi: 'این تعطیلات خیلی هزینه خواهد داشت.',
    },
    {
      sentence: 'Die Schuhe werden 50 Euro kosten.',
      english: 'The shoes will cost 50 euros.',
      russian: 'Туфли будут стоить 50 евро.',
      farsi: 'این کفش‌ها 50 یورو هزینه خواهند داشت.',
    },
    {
      sentence: 'Die Tasche wird 30 Euro kosten.',
      english: 'The bag will cost 30 euros.',
      russian: 'Сумка будет стоить 30 евро.',
      farsi: 'این کیف 30 یورو هزینه خواهد داشت.',
    },
    {
      sentence: 'Das Essen wird viel kosten.',
      english: 'The food will cost a lot.',
      russian: 'Еда будет стоить дорого.',
      farsi: 'این غذا خیلی هزینه خواهد داشت.',
    },
    {
      sentence: 'Der Kurs wird 200 Euro kosten.',
      english: 'The course will cost 200 euros.',
      russian: 'Курс будет стоить 200 евро.',
      farsi: 'این دوره 200 یورو هزینه خواهد داشت.',
    },
    {
      sentence: 'Das Ticket wird 10 Euro kosten.',
      english: 'The ticket will cost 10 euros.',
      russian: 'Билет будет стоить 10 евро.',
      farsi: 'این بلیط 10 یورو هزینه خواهد داشت.',
    },
    {
      sentence: 'Das Hotel wird teuer kosten.',
      english: 'The hotel will cost a lot.',
      russian: 'Отель будет стоить дорого.',
      farsi: 'این هتل خیلی هزینه خواهد داشت.',
    },
    {
      sentence: 'Wie viel wird das Konzert kosten?',
      english: 'How much will the concert cost?',
      russian: 'Сколько будет стоить концерт?',
      farsi: 'این کنسرت چقدر هزینه خواهد داشت؟',
    },
    {
      sentence: 'Ich schicke dir eine E-Mail.',
      english: 'I am sending you an email.',
      russian: 'Я отправляю тебе письмо.',
      farsi: 'من برای تو یک ایمیل می‌فرستم.',
    },
    {
      sentence: 'Sie schickt eine Postkarte.',
      english: 'She is sending a postcard.',
      russian: 'Она отправляет открытку.',
      farsi: 'او یک کارت پستال می‌فرستد.',
    },
    {
      sentence: 'Wir schicken eine Einladung.',
      english: 'We are sending an invitation.',
      russian: 'Мы отправляем приглашение.',
      farsi: 'ما یک دعوتنامه می‌فرستیم.',
    },
    {
      sentence: 'Er schickt ein Paket.',
      english: 'He is sending a package.',
      russian: 'Он отправляет посылку.',
      farsi: 'او یک بسته می‌فرستد.',
    },
    {
      sentence: 'Schickst du einen Brief?',
      english: 'Are you sending a letter?',
      russian: 'Ты отправляешь письмо?',
      farsi: 'آیا تو یک نامه می‌فرستی؟',
    },
    {
      sentence: 'Ich schicke eine SMS.',
      english: 'I am sending a text message.',
      russian: 'Я отправляю СМС.',
      farsi: 'من یک پیامک می‌فرستم.',
    },
    {
      sentence: 'Wir schicken ein Geschenk.',
      english: 'We are sending a gift.',
      russian: 'Мы отправляем подарок.',
      farsi: 'ما یک هدیه می‌فرستیم.',
    },
    {
      sentence: 'Sie schickt eine Nachricht.',
      english: 'She is sending a message.',
      russian: 'Она отправляет сообщение.',
      farsi: 'او یک پیام می‌فرستد.',
    },
    {
      sentence: 'Er schickt eine Bewerbung.',
      english: 'He is sending an application.',
      russian: 'Он отправляет заявление.',
      farsi: 'او یک درخواست می‌فرستد.',
    },
    {
      sentence: 'Schicken Sie ein Fax?',
      english: 'Are you sending a fax?',
      russian: 'Вы отправляете факс?',
      farsi: 'آیا شما یک فکس می‌فرستید؟',
    },
    {
      sentence: 'Ich habe dir ein Paket geschickt.',
      english: 'I sent you a package.',
      russian: 'Я отправил тебе посылку.',
      farsi: 'من برای تو یک بسته فرستادم.',
    },
    {
      sentence: 'Sie hat eine Postkarte geschickt.',
      english: 'She sent a postcard.',
      russian: 'Она отправила открытку.',
      farsi: 'او یک کارت پستال فرستاد.',
    },
    {
      sentence: 'Wir haben eine Einladung geschickt.',
      english: 'We sent an invitation.',
      russian: 'Мы отправили приглашение.',
      farsi: 'ما یک دعوتنامه فرستادیم.',
    },
    {
      sentence: 'Er hat ein Geschenk geschickt.',
      english: 'He sent a gift.',
      russian: 'Он отправил подарок.',
      farsi: 'او یک هدیه فرستاد.',
    },
    {
      sentence: 'Ich habe eine SMS geschickt.',
      english: 'I sent a text message.',
      russian: 'Я отправил СМС.',
      farsi: 'من یک پیامک فرستادم.',
    },
    {
      sentence: 'Wir haben eine Nachricht geschickt.',
      english: 'We sent a message.',
      russian: 'Мы отправили сообщение.',
      farsi: 'ما یک پیام فرستادیم.',
    },
    {
      sentence: 'Sie hat eine Bewerbung geschickt.',
      english: 'She sent an application.',
      russian: 'Она отправила заявление.',
      farsi: 'او یک درخواست فرستاد.',
    },
    {
      sentence: 'Er hat einen Brief geschickt.',
      english: 'He sent a letter.',
      russian: 'Он отправил письмо.',
      farsi: 'او یک نامه فرستاد.',
    },
    {
      sentence: 'Schickst du mir die Unterlagen?',
      english: 'Did you send me the documents?',
      russian: 'Ты отправил мне документы?',
      farsi: 'آیا تو مدارک را برای من فرستادی؟',
    },
    {
      sentence: 'Wir haben dir ein Fax geschickt.',
      english: 'We sent you a fax.',
      russian: 'Мы отправили тебе факс.',
      farsi: 'ما برای تو یک فکس فرستادیم.',
    },
    {
      sentence: 'Ich werde dir morgen eine E-Mail schicken.',
      english: 'I will send you an email tomorrow.',
      russian: 'Я отправлю тебе письмо завтра.',
      farsi: 'من فردا برای تو یک ایمیل خواهم فرستاد.',
    },
    {
      sentence: 'Sie wird eine Postkarte schicken.',
      english: 'She will send a postcard.',
      russian: 'Она отправит открытку.',
      farsi: 'او یک کارت پستال خواهد فرستاد.',
    },
    {
      sentence: 'Wir werden eine Einladung schicken.',
      english: 'We will send an invitation.',
      russian: 'Мы отправим приглашение.',
      farsi: 'ما یک دعوتنامه خواهیم فرستاد.',
    },
    {
      sentence: 'Er wird ein Paket schicken.',
      english: 'He will send a package.',
      russian: 'Он отправит посылку.',
      farsi: 'او یک بسته خواهد فرستاد.',
    },
    {
      sentence: 'Wirst du mir die Fotos schicken?',
      english: 'Will you send me the photos?',
      russian: 'Ты отправишь мне фотографии?',
      farsi: 'آیا تو عکس‌ها را برای من خواهی فرستاد؟',
    },
    {
      sentence: 'Ich werde eine SMS schicken.',
      english: 'I will send a text message.',
      russian: 'Я отправлю СМС.',
      farsi: 'من یک پیامک خواهم فرستاد.',
    },
    {
      sentence: 'Wir werden ein Geschenk schicken.',
      english: 'We will send a gift.',
      russian: 'Мы отправим подарок.',
      farsi: 'ما یک هدیه خواهیم فرستاد.',
    },
    {
      sentence: 'Sie werden eine Nachricht schicken.',
      english: 'They will send a message.',
      russian: 'Они отправят сообщение.',
      farsi: 'آنها یک پیام خواهند فرستاد.',
    },
    {
      sentence: 'Er wird eine Bewerbung schicken.',
      english: 'He will send an application.',
      russian: 'Он отправит заявление.',
      farsi: 'او یک درخواست خواهد فرستاد.',
    },
    {
      sentence: 'Wirst du mir die Details schicken?',
      english: 'Will you send me the details?',
      russian: 'Ты отправишь мне детали?',
      farsi: 'آیا تو جزئیات را برای من خواهی فرستاد؟',
    },
  ],
};

export default verben_02;
